using Dapper;
using MdwConteudos.Api.Infrastructure;

namespace MdwConteudos.Api.Modules.Cadastros;

public interface ICadastrosService
{
    Task<IEnumerable<UnidadeDto>> ListUnidades(CancellationToken ct); Task CreateUnidade(UnidadeRequest request, int user, CancellationToken ct); Task<bool> UpdateUnidade(int id, UnidadeRequest request, int user, CancellationToken ct); Task<bool> DeleteUnidade(int id, CancellationToken ct);
    Task<IEnumerable<LinguagemDto>> ListLinguagens(CancellationToken ct); Task CreateLinguagem(NomeRequest request, CancellationToken ct); Task<bool> UpdateLinguagem(int id, NomeRequest request, CancellationToken ct); Task<bool> DeleteLinguagem(int id, CancellationToken ct);
    Task<IEnumerable<EspecialidadeDto>> ListEspecialidades(CancellationToken ct); Task CreateEspecialidade(EspecialidadeRequest request, int user, CancellationToken ct); Task<bool> UpdateEspecialidade(int id, EspecialidadeRequest request, int user, CancellationToken ct); Task<bool> DeleteEspecialidade(int id, CancellationToken ct);
    Task<IEnumerable<CodigoUniversalDto>> ListCodigos(string? search, CancellationToken ct); Task CreateCodigo(CodigoUniversalRequest request, CancellationToken ct); Task<bool> UpdateCodigo(int id, CodigoUniversalRequest request, CancellationToken ct); Task<bool> DeleteCodigo(int id, CancellationToken ct);
    Task<IEnumerable<TipoAutorDto>> ListTiposAutor(CancellationToken ct); Task CreateTipoAutor(TipoAutorRequest request, CancellationToken ct); Task<bool> UpdateTipoAutor(int id, TipoAutorRequest request, CancellationToken ct); Task<bool> DeleteTipoAutor(int id, CancellationToken ct);
    Task<IEnumerable<AutorDto>> ListAutores(CancellationToken ct); Task CreateAutor(AutorRequest request, CancellationToken ct); Task<bool> UpdateAutor(int id, AutorRequest request, CancellationToken ct); Task<bool> DeleteAutor(int id, CancellationToken ct);
    Task<IEnumerable<PacoteDto>> ListPacotes(CancellationToken ct); Task<IEnumerable<ScriptPacoteDto>> ListScriptsPacotes(CancellationToken ct); Task CreatePacote(PacoteRequest request, int user, CancellationToken ct); Task<bool> UpdatePacote(int id, PacoteRequest request, int user, CancellationToken ct); Task<bool> DeletePacote(int id, CancellationToken ct);
    Task<IEnumerable<GrupoVariavelDto>> ListGruposVariaveis(CancellationToken ct); Task<IEnumerable<VariavelGrupoDto>> ListVariaveisGrupos(CancellationToken ct); Task CreateGrupoVariavel(GrupoVariavelRequest request, CancellationToken ct); Task<bool> UpdateGrupoVariavel(int id, GrupoVariavelRequest request, CancellationToken ct); Task<bool> DeleteGrupoVariavel(int id, CancellationToken ct); Task AssociateVariaveis(AssociarGrupoRequest request, CancellationToken ct);
    Task<IEnumerable<GrupoClassificacaoDto>> ListGruposClassificacoes(CancellationToken ct); Task<IEnumerable<ClassificacaoDto>> ListClassificacoes(int? groupId, CancellationToken ct); Task CreateGrupoClassificacao(GrupoClassificacaoRequest request, int user, CancellationToken ct); Task<bool> UpdateGrupoClassificacao(int id, GrupoClassificacaoRequest request, int user, CancellationToken ct); Task<bool> DeleteGrupoClassificacao(int id, CancellationToken ct); Task CreateClassificacao(ClassificacaoRequest request, int user, CancellationToken ct); Task<bool> UpdateClassificacao(int id, ClassificacaoRequest request, int user, CancellationToken ct); Task<bool> DeleteClassificacao(int id, CancellationToken ct);
}

public sealed class CadastrosService(IFirebirdConnectionFactory db) : ICadastrosService
{
    private static CommandDefinition Cmd(string sql, object? args, CancellationToken ct, System.Data.IDbTransaction? transaction = null) => new(sql, args, transaction, cancellationToken: ct);
    private static string Required(string? value, string field = "Nome") => !string.IsNullOrWhiteSpace(value) ? value.Trim() : throw new InvalidOperationException($"{field} é obrigatório.");
    private static async Task EnsureUnique(FirebirdSql.Data.FirebirdClient.FbConnection conn, string sql, object args, string message, CancellationToken ct)
    { if (await conn.ExecuteScalarAsync<int?>(Cmd(sql, args, ct)) is not null) throw new InvalidOperationException(message); }

    public async Task<IEnumerable<UnidadeDto>> ListUnidades(CancellationToken ct) { await using var c=await db.OpenConnectionAsync(ct); return await c.QueryAsync<UnidadeDto>(Cmd("SELECT CODUNIDADEMEDIDA CodUnidadeMedida, DESCRICAO Descricao, STATUS Status FROM UNIDADEMEDIDA ORDER BY DESCRICAO", null, ct)); }
    public async Task CreateUnidade(UnidadeRequest r,int u,CancellationToken ct){var n=Required(r.Descricao,"Descrição");await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM UNIDADEMEDIDA WHERE UPPER(DESCRICAO)=UPPER(@n)",new{n},"Unidade já cadastrada.",ct);await c.ExecuteAsync(Cmd("INSERT INTO UNIDADEMEDIDA (DESCRICAO,STATUS,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (@n,@s,@u,@d)",new{n,s=r.Status,u,d=DateTime.Now},ct));}
    public async Task<bool> UpdateUnidade(int id,UnidadeRequest r,int u,CancellationToken ct){var n=Required(r.Descricao,"Descrição");await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM UNIDADEMEDIDA WHERE UPPER(DESCRICAO)=UPPER(@n) AND CODUNIDADEMEDIDA<>@id",new{n,id},"Unidade já cadastrada.",ct);return await c.ExecuteAsync(Cmd("UPDATE UNIDADEMEDIDA SET DESCRICAO=@n,STATUS=@s,CODUSUARIO=@u,DTHRULTMODIFICACAO=@d WHERE CODUNIDADEMEDIDA=@id",new{n,s=r.Status,u,d=DateTime.Now,id},ct))>0;}
    public async Task<bool> DeleteUnidade(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.ExecuteAsync(Cmd("DELETE FROM UNIDADEMEDIDA WHERE CODUNIDADEMEDIDA=@id",new{id},ct))>0;}

    public async Task<IEnumerable<LinguagemDto>> ListLinguagens(CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<LinguagemDto>(Cmd("SELECT CODLINGUAGEM CodLinguagem, NOME Nome FROM TIPOLINGUAGEM ORDER BY NOME",null,ct));}
    public async Task CreateLinguagem(NomeRequest r,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM TIPOLINGUAGEM WHERE UPPER(NOME)=UPPER(@n)",new{n},"Linguagem já cadastrada.",ct);await c.ExecuteAsync(Cmd("INSERT INTO TIPOLINGUAGEM (NOME) VALUES (@n)",new{n},ct));}
    public async Task<bool> UpdateLinguagem(int id,NomeRequest r,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM TIPOLINGUAGEM WHERE UPPER(NOME)=UPPER(@n) AND CODLINGUAGEM<>@id",new{n,id},"Linguagem já cadastrada.",ct);return await c.ExecuteAsync(Cmd("UPDATE TIPOLINGUAGEM SET NOME=@n WHERE CODLINGUAGEM=@id",new{n,id},ct))>0;}
    public async Task<bool> DeleteLinguagem(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.ExecuteAsync(Cmd("DELETE FROM TIPOLINGUAGEM WHERE CODLINGUAGEM=@id",new{id},ct))>0;}

    public async Task<IEnumerable<EspecialidadeDto>> ListEspecialidades(CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<EspecialidadeDto>(Cmd("SELECT CODESPECIALIDADE CodEspecialidade, NOME Nome FROM ESPECIALIDADE ORDER BY NOME",null,ct));}
    public async Task CreateEspecialidade(EspecialidadeRequest r,int u,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM ESPECIALIDADE WHERE UPPER(NOME)=UPPER(@n)",new{n},"Especialidade já cadastrada.",ct);await c.ExecuteAsync(Cmd("INSERT INTO ESPECIALIDADE (NOME,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (@n,@u,@d)",new{n,u,d=DateTime.Now},ct));}
    public async Task<bool> UpdateEspecialidade(int id,EspecialidadeRequest r,int u,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM ESPECIALIDADE WHERE UPPER(NOME)=UPPER(@n) AND CODESPECIALIDADE<>@id",new{n,id},"Especialidade já cadastrada.",ct);return await c.ExecuteAsync(Cmd("UPDATE ESPECIALIDADE SET NOME=@n,CODUSUARIO=@u,DTHRULTMODIFICACAO=@d WHERE CODESPECIALIDADE=@id",new{n,u,d=DateTime.Now,id},ct))>0;}
    public async Task<bool> DeleteEspecialidade(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.ExecuteAsync(Cmd("DELETE FROM ESPECIALIDADE WHERE CODESPECIALIDADE=@id",new{id},ct))>0;}

    public async Task<IEnumerable<CodigoUniversalDto>> ListCodigos(string? search,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);const string select="SELECT COD_UNIVERSAL CodUniversal,TIPO_CODIGO TipoCodigo,CODIGO Codigo,DESCRICAO Descricao,UNIDADE Unidade,DESCRICAOPTBR DescricaoPtBr FROM CODIGOUNIVERSAL";if(string.IsNullOrWhiteSpace(search))return await c.QueryAsync<CodigoUniversalDto>(Cmd($"{select} ORDER BY TIPO_CODIGO,CODIGO",null,ct));var q=$"%{search.Trim()}%";return await c.QueryAsync<CodigoUniversalDto>(Cmd($"{select} WHERE UPPER(CODIGO) LIKE UPPER(@q) OR UPPER(DESCRICAO) LIKE UPPER(@q) OR UPPER(DESCRICAOPTBR) LIKE UPPER(@q) ORDER BY TIPO_CODIGO,CODIGO",new{q},ct));}
    public async Task CreateCodigo(CodigoUniversalRequest r,CancellationToken ct){var t=Required(r.TipoCodigo,"Tipo");var co=Required(r.Codigo,"Código");await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM CODIGOUNIVERSAL WHERE UPPER(TIPO_CODIGO)=UPPER(@t) AND UPPER(CODIGO)=UPPER(@co)",new{t,co},"Código universal já cadastrado.",ct);await c.ExecuteAsync(Cmd("INSERT INTO CODIGOUNIVERSAL (TIPO_CODIGO,CODIGO,DESCRICAO,UNIDADE,DESCRICAOPTBR) VALUES (@t,@co,@Descricao,@Unidade,@DescricaoPtBr)",new{t,co,r.Descricao,r.Unidade,r.DescricaoPtBr},ct));}
    public async Task<bool> UpdateCodigo(int id,CodigoUniversalRequest r,CancellationToken ct){var t=Required(r.TipoCodigo,"Tipo");var co=Required(r.Codigo,"Código");await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM CODIGOUNIVERSAL WHERE UPPER(TIPO_CODIGO)=UPPER(@t) AND UPPER(CODIGO)=UPPER(@co) AND COD_UNIVERSAL<>@id",new{t,co,id},"Código universal já cadastrado.",ct);return await c.ExecuteAsync(Cmd("UPDATE CODIGOUNIVERSAL SET TIPO_CODIGO=@t,CODIGO=@co,DESCRICAO=@Descricao,UNIDADE=@Unidade,DESCRICAOPTBR=@DescricaoPtBr WHERE COD_UNIVERSAL=@id",new{t,co,r.Descricao,r.Unidade,r.DescricaoPtBr,id},ct))>0;}
    public async Task<bool> DeleteCodigo(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.ExecuteAsync(Cmd("DELETE FROM CODIGOUNIVERSAL WHERE COD_UNIVERSAL=@id",new{id},ct))>0;}

    public async Task<IEnumerable<TipoAutorDto>> ListTiposAutor(CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<TipoAutorDto>(Cmd("SELECT CODTIPO CodTipo,DESCRICAO Descricao FROM TIPOAUTOR ORDER BY DESCRICAO",null,ct));}
    public async Task CreateTipoAutor(TipoAutorRequest r,CancellationToken ct){var n=Required(r.Descricao,"Descrição");await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM TIPOAUTOR WHERE UPPER(DESCRICAO)=UPPER(@n)",new{n},"Tipo de autor já cadastrado.",ct);await c.ExecuteAsync(Cmd("INSERT INTO TIPOAUTOR (DESCRICAO) VALUES (@n)",new{n},ct));}
    public async Task<bool> UpdateTipoAutor(int id,TipoAutorRequest r,CancellationToken ct){var n=Required(r.Descricao,"Descrição");await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM TIPOAUTOR WHERE UPPER(DESCRICAO)=UPPER(@n) AND CODTIPO<>@id",new{n,id},"Tipo de autor já cadastrado.",ct);return await c.ExecuteAsync(Cmd("UPDATE TIPOAUTOR SET DESCRICAO=@n WHERE CODTIPO=@id",new{n,id},ct))>0;}
    public async Task<bool> DeleteTipoAutor(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);if(await c.ExecuteScalarAsync<int>(Cmd("SELECT COUNT(*) FROM AUTORES WHERE CODTIPO=@id",new{id},ct))>0)throw new InvalidOperationException("Tipo de autor está em uso.");return await c.ExecuteAsync(Cmd("DELETE FROM TIPOAUTOR WHERE CODTIPO=@id",new{id},ct))>0;}
    public async Task<IEnumerable<AutorDto>> ListAutores(CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<AutorDto>(Cmd("SELECT A.CODAUTOR CodAutor,A.NOME Nome,A.ABREVIACAO Abreviacao,A.ORCID Orcid,A.PAIS Pais,A.URL Url,A.CODTIPO CodTipo,T.DESCRICAO Tipo FROM AUTORES A LEFT JOIN TIPOAUTOR T ON T.CODTIPO=A.CODTIPO ORDER BY A.NOME",null,ct));}
    public async Task CreateAutor(AutorRequest r,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM AUTORES WHERE UPPER(NOME)=UPPER(@n)",new{n},"Autor já cadastrado.",ct);await c.ExecuteAsync(Cmd("INSERT INTO AUTORES (NOME,ABREVIACAO,ORCID,PAIS,URL,CODTIPO) VALUES (@n,@Abreviacao,@Orcid,@Pais,@Url,@CodTipo)",new{n,r.Abreviacao,r.Orcid,r.Pais,r.Url,r.CodTipo},ct));}
    public async Task<bool> UpdateAutor(int id,AutorRequest r,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM AUTORES WHERE UPPER(NOME)=UPPER(@n) AND CODAUTOR<>@id",new{n,id},"Autor já cadastrado.",ct);return await c.ExecuteAsync(Cmd("UPDATE AUTORES SET NOME=@n,ABREVIACAO=@Abreviacao,ORCID=@Orcid,PAIS=@Pais,URL=@Url,CODTIPO=@CodTipo WHERE CODAUTOR=@id",new{n,r.Abreviacao,r.Orcid,r.Pais,r.Url,r.CodTipo,id},ct))>0;}
    public async Task<bool> DeleteAutor(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.ExecuteAsync(Cmd("DELETE FROM AUTORES WHERE CODAUTOR=@id",new{id},ct))>0;}

    public async Task<IEnumerable<PacoteDto>> ListPacotes(CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<PacoteDto>(Cmd("SELECT P.CODPACOTE CodPacote,P.NOME Nome,P.DESCRICAO Descricao,P.DTHRULTMODIFICACAO DataAlteracao,COUNT(S.CODSCRIPTLAUDO) QuantidadeScripts FROM PACOTES P LEFT JOIN SCRIPTLAUDO S ON S.CODPACOTE=P.CODPACOTE GROUP BY P.CODPACOTE,P.NOME,P.DESCRICAO,P.DTHRULTMODIFICACAO ORDER BY P.NOME",null,ct));}
    public async Task<IEnumerable<ScriptPacoteDto>> ListScriptsPacotes(CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<ScriptPacoteDto>(Cmd("SELECT CODSCRIPTLAUDO CodScriptLaudo,NOME Nome,CODPACOTE CodPacote FROM SCRIPTLAUDO ORDER BY NOME",null,ct));}
    public async Task CreatePacote(PacoteRequest r,int u,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM PACOTES WHERE UPPER(NOME)=UPPER(@n)",new{n},"Pacote já cadastrado.",ct);await using var tx=await c.BeginTransactionAsync(ct);try{var id=await c.ExecuteScalarAsync<int>(Cmd("INSERT INTO PACOTES (NOME,DESCRICAO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (@n,@Descricao,@u,@d) RETURNING CODPACOTE",new{n,r.Descricao,u,d=DateTime.Now},ct,tx));await SetScripts(c,tx,id,r.CodigosScripts,ct);await tx.CommitAsync(ct);}catch{await tx.RollbackAsync(ct);throw;}}
    public async Task<bool> UpdatePacote(int id,PacoteRequest r,int u,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM PACOTES WHERE UPPER(NOME)=UPPER(@n) AND CODPACOTE<>@id",new{n,id},"Pacote já cadastrado.",ct);await using var tx=await c.BeginTransactionAsync(ct);try{var rows=await c.ExecuteAsync(Cmd("UPDATE PACOTES SET NOME=@n,DESCRICAO=@Descricao,CODUSUARIO=@u,DTHRULTMODIFICACAO=@d WHERE CODPACOTE=@id",new{n,r.Descricao,u,d=DateTime.Now,id},ct,tx));if(rows>0)await SetScripts(c,tx,id,r.CodigosScripts,ct);await tx.CommitAsync(ct);return rows>0;}catch{await tx.RollbackAsync(ct);throw;}}
    private static async Task SetScripts(FirebirdSql.Data.FirebirdClient.FbConnection c,System.Data.Common.DbTransaction tx,int id,IReadOnlyList<int>? scripts,CancellationToken ct){if(scripts is null)return;await c.ExecuteAsync(Cmd("UPDATE SCRIPTLAUDO SET CODPACOTE=NULL WHERE CODPACOTE=@id",new{id},ct,tx));if(scripts.Count>0)await c.ExecuteAsync(Cmd("UPDATE SCRIPTLAUDO SET CODPACOTE=@id WHERE CODSCRIPTLAUDO IN @scripts",new{id,scripts},ct,tx));}
    public async Task<bool> DeletePacote(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);try{await c.ExecuteAsync(Cmd("UPDATE SCRIPTLAUDO SET CODPACOTE=NULL WHERE CODPACOTE=@id",new{id},ct,tx));var rows=await c.ExecuteAsync(Cmd("DELETE FROM PACOTES WHERE CODPACOTE=@id",new{id},ct,tx));await tx.CommitAsync(ct);return rows>0;}catch{await tx.RollbackAsync(ct);throw;}}

    public async Task<IEnumerable<GrupoVariavelDto>> ListGruposVariaveis(CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<GrupoVariavelDto>(Cmd("SELECT G.CODGRUPO CodGrupo,G.NOME Nome,G.DESCRICAO Descricao,G.ATIVO Ativo,COUNT(V.CODVARIAVEL) QuantidadeVariaveis FROM GRUPOSVARIAVEIS G LEFT JOIN VARIAVEIS V ON V.CODGRUPO=G.CODGRUPO GROUP BY G.CODGRUPO,G.NOME,G.DESCRICAO,G.ATIVO ORDER BY G.NOME",null,ct));}
    public async Task<IEnumerable<VariavelGrupoDto>> ListVariaveisGrupos(CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<VariavelGrupoDto>(Cmd("SELECT CODVARIAVEL CodVariavel,NOME Nome,VARIAVEL Variavel,CODGRUPO CodGrupo FROM VARIAVEIS ORDER BY NOME",null,ct));}
    public async Task CreateGrupoVariavel(GrupoVariavelRequest r,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM GRUPOSVARIAVEIS WHERE UPPER(NOME)=UPPER(@n)",new{n},"Grupo já cadastrado.",ct);await c.ExecuteAsync(Cmd("INSERT INTO GRUPOSVARIAVEIS (NOME,DESCRICAO,ATIVO,DTHRULTMODIFICACAO) VALUES (@n,@Descricao,@Ativo,@d)",new{n,r.Descricao,r.Ativo,d=DateTime.Now},ct));}
    public async Task<bool> UpdateGrupoVariavel(int id,GrupoVariavelRequest r,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM GRUPOSVARIAVEIS WHERE UPPER(NOME)=UPPER(@n) AND CODGRUPO<>@id",new{n,id},"Grupo já cadastrado.",ct);return await c.ExecuteAsync(Cmd("UPDATE GRUPOSVARIAVEIS SET NOME=@n,DESCRICAO=@Descricao,ATIVO=@Ativo,DTHRULTMODIFICACAO=@d WHERE CODGRUPO=@id",new{n,r.Descricao,r.Ativo,d=DateTime.Now,id},ct))>0;}
    public async Task<bool> DeleteGrupoVariavel(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);if(await c.ExecuteScalarAsync<int>(Cmd("SELECT COUNT(*) FROM VARIAVEIS WHERE CODGRUPO=@id",new{id},ct))>0)throw new InvalidOperationException("Grupo possui variáveis associadas.");return await c.ExecuteAsync(Cmd("DELETE FROM GRUPOSVARIAVEIS WHERE CODGRUPO=@id",new{id},ct))>0;}
    public async Task AssociateVariaveis(AssociarGrupoRequest r,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);if(r.CodigosVariaveis.Count>0)await c.ExecuteAsync(Cmd("UPDATE VARIAVEIS SET CODGRUPO=@CodGrupo,DTHRULTMODIFICACAO=@d WHERE CODVARIAVEL IN @CodigosVariaveis",new{r.CodGrupo,d=DateTime.Now,r.CodigosVariaveis},ct));}

    public async Task<IEnumerable<GrupoClassificacaoDto>> ListGruposClassificacoes(CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<GrupoClassificacaoDto>(Cmd("SELECT G.CODGRUPO CodGrupo,G.NOME Nome,COUNT(C.CODCLASSIFICACAO) QuantidadeClassificacoes FROM GRUPOSCLASSIFICACOES G LEFT JOIN CLASSIFICACOES C ON C.CODGRUPO=G.CODGRUPO GROUP BY G.CODGRUPO,G.NOME ORDER BY G.NOME",null,ct));}
    public async Task<IEnumerable<ClassificacaoDto>> ListClassificacoes(int? groupId,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);return await c.QueryAsync<ClassificacaoDto>(Cmd("SELECT CODCLASSIFICACAO CodClassificacao,NOME Nome,CODGRUPO CodGrupo FROM CLASSIFICACOES WHERE @groupId IS NULL OR CODGRUPO=@groupId ORDER BY NOME",new{groupId},ct));}
    public async Task CreateGrupoClassificacao(GrupoClassificacaoRequest r,int u,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM GRUPOSCLASSIFICACOES WHERE UPPER(NOME)=UPPER(@n)",new{n},"Grupo já cadastrado.",ct);await c.ExecuteAsync(Cmd("INSERT INTO GRUPOSCLASSIFICACOES (NOME,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (@n,@u,@d)",new{n,u,d=DateTime.Now},ct));}
    public async Task<bool> UpdateGrupoClassificacao(int id,GrupoClassificacaoRequest r,int u,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM GRUPOSCLASSIFICACOES WHERE UPPER(NOME)=UPPER(@n) AND CODGRUPO<>@id",new{n,id},"Grupo já cadastrado.",ct);return await c.ExecuteAsync(Cmd("UPDATE GRUPOSCLASSIFICACOES SET NOME=@n,CODUSUARIO=@u,DTHRULTMODIFICACAO=@d WHERE CODGRUPO=@id",new{n,u,d=DateTime.Now,id},ct))>0;}
    public async Task<bool> DeleteGrupoClassificacao(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);if(await c.ExecuteScalarAsync<int>(Cmd("SELECT COUNT(*) FROM CLASSIFICACOES WHERE CODGRUPO=@id",new{id},ct))>0)throw new InvalidOperationException("Grupo possui classificações associadas.");return await c.ExecuteAsync(Cmd("DELETE FROM GRUPOSCLASSIFICACOES WHERE CODGRUPO=@id",new{id},ct))>0;}
    public async Task CreateClassificacao(ClassificacaoRequest r,int u,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM CLASSIFICACOES WHERE UPPER(NOME)=UPPER(@n)",new{n},"Classificação já cadastrada.",ct);await c.ExecuteAsync(Cmd("INSERT INTO CLASSIFICACOES (NOME,CODGRUPO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (@n,@g,@u,@d)",new{n,g=r.CodGrupo,u,d=DateTime.Now},ct));}
    public async Task<bool> UpdateClassificacao(int id,ClassificacaoRequest r,int u,CancellationToken ct){var n=Required(r.Nome);await using var c=await db.OpenConnectionAsync(ct);await EnsureUnique(c,"SELECT 1 FROM CLASSIFICACOES WHERE UPPER(NOME)=UPPER(@n) AND CODCLASSIFICACAO<>@id",new{n,id},"Classificação já cadastrada.",ct);return await c.ExecuteAsync(Cmd("UPDATE CLASSIFICACOES SET NOME=@n,CODGRUPO=@g,CODUSUARIO=@u,DTHRULTMODIFICACAO=@d WHERE CODCLASSIFICACAO=@id",new{n,g=r.CodGrupo,u,d=DateTime.Now,id},ct))>0;}
    public async Task<bool> DeleteClassificacao(int id,CancellationToken ct){await using var c=await db.OpenConnectionAsync(ct);if(await c.ExecuteScalarAsync<int>(Cmd("SELECT COUNT(*) FROM VARIAVEIS_CLASSIFICACOES WHERE CODCLASSIFICACAO=@id",new{id},ct))>0)throw new InvalidOperationException("Classificação está vinculada a variáveis.");return await c.ExecuteAsync(Cmd("DELETE FROM CLASSIFICACOES WHERE CODCLASSIFICACAO=@id",new{id},ct))>0;}
}
