using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MdwConteudos.Api.Infrastructure;
using MdwConteudos.Api.Services;

namespace MdwConteudos.Api.Modules.Cadastros;

[ApiController, Authorize]
public abstract class CadastrosControllerBase : ControllerBase
{
    protected IActionResult Data<T>(IEnumerable<T> rows) => Ok(ApiResponse.Ok(rows, rows.Count()));
    protected IActionResult Done(bool found, string message) => found ? Ok(ApiResponse.OkMessage(message)) : NotFound(ApiResponse.Fail("Não encontrado"));
    protected async Task<IActionResult> Write(Func<Task<IActionResult>> action)
    { try { return await action(); } catch (InvalidOperationException ex) { return Conflict(ApiResponse.Fail("Validação", ex.Message)); } catch (Exception ex) { return BadRequest(ApiResponse.Fail("Não foi possível concluir a operação", ex.Message)); } }
}

[Route("api/web/cadastros/unidades")]
public sealed class UnidadesController(ICadastrosService s):CadastrosControllerBase { [HttpGet] public async Task<IActionResult> List(CancellationToken c)=>Data(await s.ListUnidades(c)); [HttpPost,Authorize(Roles="admin")] public Task<IActionResult> Create(UnidadeRequest r,CancellationToken c)=>Write(async()=>{await s.CreateUnidade(r,User.GetCodUsuario(),c);return Ok(ApiResponse.OkMessage("Unidade cadastrada."));}); [HttpPut("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Update(int id,UnidadeRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdateUnidade(id,r,User.GetCodUsuario(),c),"Unidade atualizada.")); [HttpDelete("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Delete(int id,CancellationToken c)=>Write(async()=>Done(await s.DeleteUnidade(id,c),"Unidade excluída.")); }
[Route("api/web/cadastros/linguagens")]
public sealed class LinguagensController(ICadastrosService s):CadastrosControllerBase { [HttpGet] public async Task<IActionResult> List(CancellationToken c)=>Data(await s.ListLinguagens(c)); [HttpPost,Authorize(Roles="admin")] public Task<IActionResult> Create(NomeRequest r,CancellationToken c)=>Write(async()=>{await s.CreateLinguagem(r,c);return Ok(ApiResponse.OkMessage("Linguagem cadastrada."));}); [HttpPut("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Update(int id,NomeRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdateLinguagem(id,r,c),"Linguagem atualizada.")); [HttpDelete("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Delete(int id,CancellationToken c)=>Write(async()=>Done(await s.DeleteLinguagem(id,c),"Linguagem excluída.")); }
[Route("api/web/cadastros/especialidades")]
public sealed class EspecialidadesController(ICadastrosService s):CadastrosControllerBase { [HttpGet] public async Task<IActionResult> List(CancellationToken c)=>Data(await s.ListEspecialidades(c)); [HttpPost,Authorize(Roles="admin")] public Task<IActionResult> Create(EspecialidadeRequest r,CancellationToken c)=>Write(async()=>{await s.CreateEspecialidade(r,User.GetCodUsuario(),c);return Ok(ApiResponse.OkMessage("Especialidade cadastrada."));}); [HttpPut("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Update(int id,EspecialidadeRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdateEspecialidade(id,r,User.GetCodUsuario(),c),"Especialidade atualizada.")); [HttpDelete("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Delete(int id,CancellationToken c)=>Write(async()=>Done(await s.DeleteEspecialidade(id,c),"Especialidade excluída.")); }
[Route("api/web/cadastros/codigos-universais")]
public sealed class CodigosUniversaisController(ICadastrosService s):CadastrosControllerBase { [HttpGet] public async Task<IActionResult> List(string? search,CancellationToken c)=>Data(await s.ListCodigos(search,c)); [HttpPost,Authorize(Roles="admin")] public Task<IActionResult> Create(CodigoUniversalRequest r,CancellationToken c)=>Write(async()=>{await s.CreateCodigo(r,c);return Ok(ApiResponse.OkMessage("Código cadastrado."));}); [HttpPut("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Update(int id,CodigoUniversalRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdateCodigo(id,r,c),"Código atualizado.")); [HttpDelete("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Delete(int id,CancellationToken c)=>Write(async()=>Done(await s.DeleteCodigo(id,c),"Código excluído.")); }
[Route("api/web/cadastros/autores")]
public sealed class AutoresController(ICadastrosService s):CadastrosControllerBase { [HttpGet] public async Task<IActionResult> List(CancellationToken c)=>Data(await s.ListAutores(c)); [HttpPost,Authorize(Roles="admin")] public Task<IActionResult> Create(AutorRequest r,CancellationToken c)=>Write(async()=>{await s.CreateAutor(r,c);return Ok(ApiResponse.OkMessage("Autor cadastrado."));}); [HttpPut("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Update(int id,AutorRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdateAutor(id,r,c),"Autor atualizado.")); [HttpDelete("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Delete(int id,CancellationToken c)=>Write(async()=>Done(await s.DeleteAutor(id,c),"Autor excluído.")); [HttpGet("tipos")] public async Task<IActionResult> Types(CancellationToken c)=>Data(await s.ListTiposAutor(c)); [HttpPost("tipos"),Authorize(Roles="admin")] public Task<IActionResult> CreateType(TipoAutorRequest r,CancellationToken c)=>Write(async()=>{await s.CreateTipoAutor(r,c);return Ok(ApiResponse.OkMessage("Tipo cadastrado."));}); [HttpPut("tipos/{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> UpdateType(int id,TipoAutorRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdateTipoAutor(id,r,c),"Tipo atualizado.")); [HttpDelete("tipos/{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> DeleteType(int id,CancellationToken c)=>Write(async()=>Done(await s.DeleteTipoAutor(id,c),"Tipo excluído.")); }
[Route("api/web/cadastros/pacotes")]
public sealed class PacotesController(ICadastrosService s):CadastrosControllerBase { [HttpGet] public async Task<IActionResult> List(CancellationToken c)=>Data(await s.ListPacotes(c)); [HttpGet("scripts")] public async Task<IActionResult> Scripts(CancellationToken c)=>Data(await s.ListScriptsPacotes(c)); [HttpPost,Authorize(Roles="admin")] public Task<IActionResult> Create(PacoteRequest r,CancellationToken c)=>Write(async()=>{await s.CreatePacote(r,User.GetCodUsuario(),c);return Ok(ApiResponse.OkMessage("Pacote cadastrado."));}); [HttpPut("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Update(int id,PacoteRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdatePacote(id,r,User.GetCodUsuario(),c),"Pacote atualizado.")); [HttpDelete("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Delete(int id,CancellationToken c)=>Write(async()=>Done(await s.DeletePacote(id,c),"Pacote excluído.")); }
[Route("api/web/cadastros/grupos-variaveis")]
public sealed class GruposVariaveisController(ICadastrosService s):CadastrosControllerBase { [HttpGet] public async Task<IActionResult> List(CancellationToken c)=>Data(await s.ListGruposVariaveis(c)); [HttpGet("variaveis")] public async Task<IActionResult> Variables(CancellationToken c)=>Data(await s.ListVariaveisGrupos(c)); [HttpPost,Authorize(Roles="admin")] public Task<IActionResult> Create(GrupoVariavelRequest r,CancellationToken c)=>Write(async()=>{await s.CreateGrupoVariavel(r,c);return Ok(ApiResponse.OkMessage("Grupo cadastrado."));}); [HttpPut("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Update(int id,GrupoVariavelRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdateGrupoVariavel(id,r,c),"Grupo atualizado.")); [HttpDelete("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Delete(int id,CancellationToken c)=>Write(async()=>Done(await s.DeleteGrupoVariavel(id,c),"Grupo excluído.")); [HttpPut("associacoes"),Authorize(Roles="admin")] public Task<IActionResult> Associate(AssociarGrupoRequest r,CancellationToken c)=>Write(async()=>{await s.AssociateVariaveis(r,c);return Ok(ApiResponse.OkMessage("Associações atualizadas."));}); }
[Route("api/web/cadastros/classificacoes")]
public sealed class ClassificacoesController(ICadastrosService s):CadastrosControllerBase { [HttpGet] public async Task<IActionResult> List(int? groupId,CancellationToken c)=>Data(await s.ListClassificacoes(groupId,c)); [HttpPost,Authorize(Roles="admin")] public Task<IActionResult> Create(ClassificacaoRequest r,CancellationToken c)=>Write(async()=>{await s.CreateClassificacao(r,User.GetCodUsuario(),c);return Ok(ApiResponse.OkMessage("Classificação cadastrada."));}); [HttpPut("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Update(int id,ClassificacaoRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdateClassificacao(id,r,User.GetCodUsuario(),c),"Classificação atualizada.")); [HttpDelete("{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> Delete(int id,CancellationToken c)=>Write(async()=>Done(await s.DeleteClassificacao(id,c),"Classificação excluída.")); [HttpGet("grupos")] public async Task<IActionResult> Groups(CancellationToken c)=>Data(await s.ListGruposClassificacoes(c)); [HttpPost("grupos"),Authorize(Roles="admin")] public Task<IActionResult> CreateGroup(GrupoClassificacaoRequest r,CancellationToken c)=>Write(async()=>{await s.CreateGrupoClassificacao(r,User.GetCodUsuario(),c);return Ok(ApiResponse.OkMessage("Grupo cadastrado."));}); [HttpPut("grupos/{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> UpdateGroup(int id,GrupoClassificacaoRequest r,CancellationToken c)=>Write(async()=>Done(await s.UpdateGrupoClassificacao(id,r,User.GetCodUsuario(),c),"Grupo atualizado.")); [HttpDelete("grupos/{id:int}"),Authorize(Roles="admin")] public Task<IActionResult> DeleteGroup(int id,CancellationToken c)=>Write(async()=>Done(await s.DeleteGrupoClassificacao(id,c),"Grupo excluído.")); }
