using Dapper;
using FirebirdSql.Data.FirebirdClient;
using FirebirdSql.Data.Isql;
using Microsoft.Extensions.Options;
using System.Text.Json;
using MdwConteudos.Api.Infrastructure;
using MdwConteudos.Api.Modules.Assistente.Publicacao;

namespace ConversorHtml.Tests;

public sealed class FirebirdPublicationFactAttribute : FactAttribute
{
    public FirebirdPublicationFactAttribute()
    {
        if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("PUBLICACAO_TEST_FBCLIENT")))
            Skip = "Defina PUBLICACAO_TEST_FBCLIENT para executar em dois bancos temporarios embedded.";
    }
}

public sealed class PublicacaoAssistenteTests : IAsyncLifetime
{
    private string sourceCs = "";
    private string targetCs = "";
    private PublicacaoService service = null!;

    public async Task InitializeAsync()
    {
        sourceCs = CreateDatabase();
        targetCs = CreateDatabase();
        await using var source = new FbConnection(sourceCs);
        await source.OpenAsync();
        foreach (var sql in new[] {
            "CREATE TABLE PACOTES (CODPACOTE INTEGER PRIMARY KEY,NOME VARCHAR(100))",
            "CREATE TABLE SCRIPTLAUDO (CODSCRIPTLAUDO INTEGER PRIMARY KEY,NOME VARCHAR(252),SISTEMA VARCHAR(50),LINGUAGEM VARCHAR(20),CODPACOTE INTEGER,ATIVO INTEGER,ARQUIVO_JSON BLOB SUB_TYPE BINARY,DLL BLOB SUB_TYPE BINARY,APROVADO INTEGER,APROVADO_POR VARCHAR(100),DATA_VERIFICACAO TIMESTAMP)",
            "CREATE TABLE SCRIPTVERSOES (CODVERSAO INTEGER PRIMARY KEY,CODSCRIPTLAUDO INTEGER,ATIVO CHAR(1),ARQUIVO_JSON BLOB SUB_TYPE BINARY,ARQUIVO_DLL BLOB SUB_TYPE BINARY,APROVADO CHAR(1),APROVADO_POR VARCHAR(100),DATA_APROVACAO TIMESTAMP,NUMERO_VERSAO VARCHAR(20))",
            "CREATE TABLE SCRIPTLAUDOMRD (CODSCRIPTMRD INTEGER PRIMARY KEY,CODSCRIPTLAUDO INTEGER,NOME_ARQUIVO VARCHAR(128),ARQUIVO_MRD BLOB SUB_TYPE BINARY,PADRAO CHAR(1))",
            "CREATE TABLE SCRIPTVERSAOMRD (CODVERSAOMRD INTEGER PRIMARY KEY,CODVERSAO INTEGER,NOME_ARQUIVO VARCHAR(128),ARQUIVO_MRD BLOB SUB_TYPE BINARY,PADRAO CHAR(1))" })
            await source.ExecuteAsync(sql);
        await Migrate(source, "publicacao-conteudos.sql");
        await source.ExecuteAsync("INSERT INTO PACOTES VALUES (1,'Consulta')");
        await using var target = new FbConnection(targetCs);
        await target.OpenAsync();
        foreach (var sql in new[] {
            "CREATE TABLE SCRIPTLAUDO (CODSCRIPTLAUDO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,TITULO VARCHAR(252),TIPOSCRIPT SMALLINT,ESTRUTURASCRIPT BLOB SUB_TYPE TEXT,STATUS SMALLINT,DATAMODIFICACAO TIMESTAMP)",
            "CREATE TABLE PAGFOTOS (CODPAGFOTOS INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,TITULO VARCHAR(128),ESTRUTURAPAGFOTOS BLOB SUB_TYPE TEXT,STATUS SMALLINT)",
            "CREATE TABLE ESPECIALIDADE (CODESPECIALIDADE INTEGER PRIMARY KEY,DESCRICAO VARCHAR(100))",
            "CREATE TABLE SCRIPTLAUDO_ESPECIALIDADE (CODSCRIPTLAUDO INTEGER,CODESPECIALIDADE INTEGER,PRIMARY KEY(CODSCRIPTLAUDO,CODESPECIALIDADE))",
            "CREATE TABLE SCRIPTLAUDO_PAGFOTOS (CODSCRIPTLAUDO INTEGER,CODPAGFOTOS INTEGER,SEQUENCIA SMALLINT,PRIMARY KEY(CODSCRIPTLAUDO,CODPAGFOTOS))",
            "CREATE TABLE PAGFOTOS_ESPECIALIDADE (CODPAGFOTOS INTEGER,CODESPECIALIDADE INTEGER,PRIMARY KEY(CODPAGFOTOS,CODESPECIALIDADE))",
            "CREATE TABLE PROCEDIMENTO_SCRIPTLAUDO (CODSCRIPTLAUDO INTEGER,CODPROCEDIMENTO INTEGER,PRIMARY KEY(CODSCRIPTLAUDO,CODPROCEDIMENTO))" })
            await target.ExecuteAsync(sql);
        await Migrate(target, "publicacao-assistente.sql");
        await target.ExecuteAsync("INSERT INTO ESPECIALIDADE VALUES (10,'Consulta')");
        await target.ExecuteAsync("INSERT INTO ESPECIALIDADE VALUES (20,'Local')");
        await target.ExecuteAsync("INSERT INTO ESPECIALIDADE VALUES (30,'Ecocardiografia')");
        service = new PublicacaoService(new SourceFactory(sourceCs), new TargetFactory(targetCs), Options.Create(new PublicacaoOptions { Enabled = true, SourceKey = "test" }));
        await service.SaveMapping(1, [10], default);
    }

    [FirebirdPublicationFact]
    public async Task UxWithoutMrdPublishesAndPreservesLocalInactivation()
    {
        await Seed();
        Assert.True(await service.ProcessNext(default));
        await using var target = new FbConnection(targetCs);
        var item = await target.QuerySingleAsync("SELECT * FROM SCRIPTLAUDO");
        Assert.Equal("{}", (string)item.ESTRUTURASCRIPT);
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM PAGFOTOS"));
        await target.ExecuteAsync("UPDATE SCRIPTLAUDO SET STATUS=0");
        await target.ExecuteAsync("INSERT INTO SCRIPTLAUDO_ESPECIALIDADE VALUES (1,20)");
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("UPDATE SCRIPTLAUDO SET NOME='Novo titulo'");
        await service.ProcessNext(default);
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT STATUS FROM SCRIPTLAUDO"));
        Assert.Equal(2, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO_ESPECIALIDADE"));
        Assert.Equal("Novo titulo", await target.ExecuteScalarAsync<string>("SELECT TITULO FROM SCRIPTLAUDO"));
        await Assert.ThrowsAsync<FbException>(() => target.ExecuteAsync("UPDATE SCRIPTLAUDO SET TITULO='Edicao local'"));
        Assert.False(await service.ProcessNext(default));
    }

    [FirebirdPublicationFact]
    public async Task ActiveVersionNeverFallsBackToBaseAndDeletionRequiresResume()
    {
        await Seed();
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTVERSOES (CODVERSAO,CODSCRIPTLAUDO,ATIVO,APROVADO,APROVADO_POR,DATA_APROVACAO,NUMERO_VERSAO) VALUES (1,1,'T','T','Teste',CURRENT_TIMESTAMP,'V1')");
        await service.ProcessNext(default);
        Assert.Equal("falha", await source.ExecuteScalarAsync<string>("SELECT ESTADO FROM ASS_PUBLICACAO"));
        await source.ExecuteAsync("UPDATE SCRIPTVERSOES SET ARQUIVO_JSON=@bytes", new { bytes = "{\"active\":true}"u8.ToArray() });
        await service.ProcessNext(default);
        await using var target = new FbConnection(targetCs);
        Assert.Equal("{\"active\":true}", await target.ExecuteScalarAsync<string>("SELECT ESTRUTURASCRIPT FROM SCRIPTLAUDO"));
        await target.ExecuteAsync("DELETE FROM SCRIPTLAUDO_ESPECIALIDADE");
        await target.ExecuteAsync("DELETE FROM SCRIPTLAUDO");
        await service.Enqueue(1, false, default);
        await service.ProcessNext(default);
        Assert.Equal("suspenso", await source.ExecuteScalarAsync<string>("SELECT ESTADO FROM ASS_PUBLICACAO"));
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO"));
        await service.Enqueue(1, true, default);
        await service.ProcessNext(default);
        Assert.Equal(1, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO"));
    }

    [FirebirdPublicationFact]
    public async Task SourceDeletionPreservesDestinationAndMrd()
    {
        await SeedFlex();
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTLAUDOMRD VALUES (1,1,'modelo.mrd',@bytes,'T')", new { bytes = "Medware Designer Report 1.0 test"u8.ToArray() });
        await service.ProcessNext(default);
        await using var target = new FbConnection(targetCs);
        Assert.Equal(1, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM PAGFOTOS"));
        await source.ExecuteAsync("DELETE FROM SCRIPTLAUDO");
        await service.ProcessNext(default);
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT STATUS FROM SCRIPTLAUDO"));
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT STATUS FROM PAGFOTOS"));
    }

    [FirebirdPublicationFact]
    public async Task UxPublishesLinkedJsonMrd()
    {
        await Seed();
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTLAUDOMRD VALUES (1,1,'modelo.json',@bytes,'T')", new { bytes = "{\"mrd\":true}"u8.ToArray() });
        await service.ProcessNext(default);
        await using var target = new FbConnection(targetCs);
        Assert.Equal("{\"mrd\":true}", await target.ExecuteScalarAsync<string>("SELECT ESTRUTURAPAGFOTOS FROM PAGFOTOS"));
        Assert.Equal(1, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO_PAGFOTOS"));
    }

    [FirebirdPublicationFact]
    public async Task RollbackDoesNotEnqueueAndReplayDoesNotTouchModificationDate()
    {
        await Seed();
        await service.ProcessNext(default);
        await using var target = new FbConnection(targetCs);
        var stamp = await target.ExecuteScalarAsync<DateTime>("SELECT DATAMODIFICACAO FROM SCRIPTLAUDO");
        await using var source = new FbConnection(sourceCs);
        await source.OpenAsync();
        await using (var tx = await source.BeginTransactionAsync())
        {
            await source.ExecuteAsync("UPDATE SCRIPTLAUDO SET NOME='Rollback'", transaction: tx);
            await tx.RollbackAsync();
        }
        Assert.False(await service.ProcessNext(default));
        await source.ExecuteAsync("UPDATE ASS_PUBLICACAO SET ESTADO='pendente'");
        await service.ProcessNext(default);
        Assert.Equal(stamp, await target.ExecuteScalarAsync<DateTime>("SELECT DATAMODIFICACAO FROM SCRIPTLAUDO"));
        Assert.Equal(1, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO"));
    }

    private async Task Seed()
    {
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTLAUDO VALUES (1,'Consulta','Laudos UX',NULL,1,1,@bytes,NULL,1,'Teste',CURRENT_TIMESTAMP)", new { bytes = "{}"u8.ToArray() });
    }

    private async Task SeedFlex()
    {
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTLAUDO VALUES (1,'Consulta','Laudos Flex',NULL,1,1,NULL,@bytes,1,'Teste',CURRENT_TIMESTAMP)", new { bytes = "dll"u8.ToArray() });
    }

    [FirebirdPublicationFact]
    public async Task RemappingPreservesLocalLinksAndRemovesOnlyManagedLinks()
    {
        await Seed();
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTLAUDOMRD VALUES (1,1,'modelo.json',@bytes,'T')", new { bytes = "{\"mrd\":true}"u8.ToArray() });
        await service.ProcessNext(default);
        await using var target = new FbConnection(targetCs);
        await target.ExecuteAsync("INSERT INTO ESPECIALIDADE VALUES (40,'Nova')");
        await target.ExecuteAsync("INSERT INTO SCRIPTLAUDO_ESPECIALIDADE VALUES (1,20)");
        await target.ExecuteAsync("INSERT INTO PAGFOTOS_ESPECIALIDADE VALUES (1,20)");
        await service.SaveMapping(1, [40], default);
        await service.ProcessNext(default);
        Assert.Equal(new[] { 20, 40 }, await target.QueryAsync<int>("SELECT CODESPECIALIDADE FROM SCRIPTLAUDO_ESPECIALIDADE ORDER BY 1"));
        Assert.Equal(new[] { 20, 40 }, await target.QueryAsync<int>("SELECT CODESPECIALIDADE FROM PAGFOTOS_ESPECIALIDADE ORDER BY 1"));
        await source.ExecuteAsync("DELETE FROM SCRIPTLAUDOMRD");
        await service.ProcessNext(default);
        Assert.Equal(1, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM PAGFOTOS"));
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO_PAGFOTOS"));
    }

    [FirebirdPublicationFact]
    public async Task ScriptSpecificMappingOverridesPackageMapping()
    {
        await Seed();
        await service.SaveScriptMapping(1, 1, [30], default);
        await service.ProcessNext(default);
        await using var target = new FbConnection(targetCs);
        Assert.Equal(new[] { 30 }, await target.QueryAsync<int>("SELECT CODESPECIALIDADE FROM SCRIPTLAUDO_ESPECIALIDADE ORDER BY 1"));
        await service.SaveMapping(1, [10, 20], default);
        await service.ProcessNext(default);
        Assert.Equal(new[] { 30 }, await target.QueryAsync<int>("SELECT CODESPECIALIDADE FROM SCRIPTLAUDO_ESPECIALIDADE ORDER BY 1"));
        await service.SaveScriptMapping(1, 1, [], default);
        await service.ProcessNext(default);
        Assert.Equal(new[] { 10, 20 }, await target.QueryAsync<int>("SELECT CODESPECIALIDADE FROM SCRIPTLAUDO_ESPECIALIDADE ORDER BY 1"));
    }

    [FirebirdPublicationFact]
    public async Task ChangingPackageUsesDestinationDefaultAndPreservesSpecificMapping()
    {
        await Seed();
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO PACOTES VALUES (2,'Ecocardiografia')");
        await service.SaveMapping(2, [30], default);
        await service.ProcessNext(default);
        await using var target = new FbConnection(targetCs);
        Assert.Equal(new[] { 10 }, await target.QueryAsync<int>("SELECT CODESPECIALIDADE FROM SCRIPTLAUDO_ESPECIALIDADE ORDER BY 1"));

        await source.ExecuteAsync("UPDATE SCRIPTLAUDO SET CODPACOTE=2 WHERE CODSCRIPTLAUDO=1");
        await service.ProcessNext(default);
        Assert.Equal(new[] { 30 }, await target.QueryAsync<int>("SELECT CODESPECIALIDADE FROM SCRIPTLAUDO_ESPECIALIDADE ORDER BY 1"));

        await service.SaveScriptMapping(2, 1, [20], default);
        await service.ProcessNext(default);
        await source.ExecuteAsync("UPDATE SCRIPTLAUDO SET CODPACOTE=1 WHERE CODSCRIPTLAUDO=1");
        await service.ProcessNext(default);
        Assert.Equal(new[] { 20 }, await target.QueryAsync<int>("SELECT CODESPECIALIDADE FROM SCRIPTLAUDO_ESPECIALIDADE ORDER BY 1"));
    }

    [FirebirdPublicationFact]
    public async Task PackageScriptsFiltersByActiveStatus()
    {
        await Seed();
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTLAUDO VALUES (2,'Consulta inativa','Laudos UX',NULL,1,0,@bytes,NULL,1,'Teste',CURRENT_TIMESTAMP)", new { bytes = "{}"u8.ToArray() });
        var active = JsonSerializer.SerializeToElement(await service.PackageScripts(1, 1, null, 1, default));
        var inactive = JsonSerializer.SerializeToElement(await service.PackageScripts(1, 1, null, 0, default));
        Assert.Equal(1, active.GetProperty("total").GetInt32());
        Assert.Equal(1, inactive.GetProperty("total").GetInt32());
        Assert.Equal(1, active.GetProperty("items")[0].GetProperty("Id").GetInt32());
        Assert.Equal(2, inactive.GetProperty("items")[0].GetProperty("Id").GetInt32());
    }

    [FirebirdPublicationFact]
    public async Task NotApprovedScriptWaitsForApprovalAndThenPublishes()
    {
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTLAUDO VALUES (1,'Consulta','Laudos UX',NULL,1,1,@bytes,NULL,0,NULL,NULL)", new { bytes = "{}"u8.ToArray() });
        await service.ProcessNext(default);
        Assert.Equal("aguardando_aprovacao", await source.ExecuteScalarAsync<string>("SELECT ESTADO FROM ASS_PUBLICACAO"));
        await using var target = new FbConnection(targetCs);
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO"));
        await source.ExecuteAsync("UPDATE SCRIPTLAUDO SET APROVADO=1, APROVADO_POR='Teste', DATA_VERIFICACAO=CURRENT_TIMESTAMP");
        await service.ProcessNext(default);
        Assert.Equal("sincronizado", await source.ExecuteScalarAsync<string>("SELECT ESTADO FROM ASS_PUBLICACAO"));
        Assert.Equal(1, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO"));
    }

    [FirebirdPublicationFact]
    public async Task ListIncludesUnqueuedNotApprovedScriptsInAwaitingApprovalSummary()
    {
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTLAUDO VALUES (1,'Consulta','Laudos UX',NULL,1,1,@bytes,NULL,0,NULL,NULL)", new { bytes = "{}"u8.ToArray() });
        var result = JsonSerializer.SerializeToElement(await service.List(1, null, default));
        Assert.Equal(1, result.GetProperty("total").GetInt32());
        Assert.Equal(1, result.GetProperty("summary").GetProperty("aguardando_aprovacao").GetInt32());
        Assert.Equal("aguardando_aprovacao", result.GetProperty("items")[0].GetProperty("Estado").GetString());
    }

    [FirebirdPublicationFact]
    public async Task ListIncludesDestinationSpecialties()
    {
        await Seed();
        await service.ProcessNext(default);
        var result = JsonSerializer.SerializeToElement(await service.List(1, null, default));
        var specialties = result.GetProperty("items")[0].GetProperty("EspecialidadesDestino").EnumerateArray().Select(x => x.GetString()).ToArray();
        Assert.Equal(new[] { "Consulta" }, specialties);
    }

    [FirebirdPublicationFact]
    public async Task ActiveVersionApprovalOverridesScriptApproval()
    {
        await Seed();
        await using var source = new FbConnection(sourceCs);
        await source.ExecuteAsync("INSERT INTO SCRIPTVERSOES (CODVERSAO,CODSCRIPTLAUDO,ATIVO,ARQUIVO_JSON,APROVADO,NUMERO_VERSAO) VALUES (1,1,'T',@bytes,'F','V1')", new { bytes = "{\"active\":true}"u8.ToArray() });
        await service.ProcessNext(default);
        Assert.Equal("aguardando_aprovacao", await source.ExecuteScalarAsync<string>("SELECT ESTADO FROM ASS_PUBLICACAO"));
        await using var target = new FbConnection(targetCs);
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO"));
        await source.ExecuteAsync("UPDATE SCRIPTVERSOES SET APROVADO='T', APROVADO_POR='Teste', DATA_APROVACAO=CURRENT_TIMESTAMP");
        await service.ProcessNext(default);
        Assert.Equal("{\"active\":true}", await target.ExecuteScalarAsync<string>("SELECT ESTRUTURASCRIPT FROM SCRIPTLAUDO"));
    }

    [FirebirdPublicationFact]
    public async Task ReconciliationRequiresExplicitConfirmation()
    {
        await Seed();
        await using var target = new FbConnection(targetCs);
        await target.ExecuteAsync("INSERT INTO SCRIPTLAUDO (TITULO,TIPOSCRIPT,ESTRUTURASCRIPT,STATUS) VALUES ('Consulta',3,'{}',0)");
        await service.ProcessNext(default);
        await using var source = new FbConnection(sourceCs);
        Assert.Equal("falha", await source.ExecuteScalarAsync<string>("SELECT ESTADO FROM ASS_PUBLICACAO"));
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM CON_PUBLICACAO"));
        await service.Candidates(1, default);
        await service.Reconcile(1, 1, default);
        await service.ProcessNext(default);
        Assert.Equal("sincronizado", await source.ExecuteScalarAsync<string>("SELECT ESTADO FROM ASS_PUBLICACAO"));
        Assert.Equal(1, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO"));
        Assert.Equal(0, await target.ExecuteScalarAsync<int>("SELECT STATUS FROM SCRIPTLAUDO"));
    }

    [FirebirdPublicationFact]
    public async Task ConcurrentWorkersAndManualImportDoNotDuplicate()
    {
        await Seed();
        await Task.WhenAll(service.ProcessNext(default), service.ProcessNext(default));
        await service.ImportSource(1, [10], [], default);
        await service.ImportSource(1, [10], [], default);
        await using var target = new FbConnection(targetCs);
        Assert.Equal(1, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM SCRIPTLAUDO"));
        Assert.Equal(1, await target.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM CON_PUBLICACAO"));
    }

    [FirebirdPublicationFact]
    public async Task UnavailableDestinationRetainsDurableJob()
    {
        await Seed();
        var unavailable = new PublicacaoService(new SourceFactory(sourceCs), new UnavailableFactory(), Options.Create(new PublicacaoOptions { Enabled = true, SourceKey = "test" }));
        await unavailable.ProcessNext(default);
        await using var source = new FbConnection(sourceCs);
        Assert.Equal("repetir", await source.ExecuteScalarAsync<string>("SELECT ESTADO FROM ASS_PUBLICACAO"));
        Assert.Equal(1, await source.ExecuteScalarAsync<int>("SELECT TENTATIVAS FROM ASS_PUBLICACAO"));
        await source.ExecuteAsync("UPDATE ASS_PUBLICACAO SET PROXIMA=CURRENT_TIMESTAMP");
        await service.ProcessNext(default);
        Assert.Equal("sincronizado", await source.ExecuteScalarAsync<string>("SELECT ESTADO FROM ASS_PUBLICACAO"));
    }

    private sealed class UnavailableFactory : IAssistantFirebirdConnectionFactory
    {
        public Task<FbConnection> OpenConnectionAsync(CancellationToken ct = default) => throw new IOException("Simulated outage");
    }

    private static string CreateDatabase()
    {
        var cs = new FbConnectionStringBuilder {
            Database = Path.Combine(Path.GetTempPath(), $"publicacao-test-{Guid.NewGuid():N}.fdb"),
            ServerType = FbServerType.Embedded, ClientLibrary = Environment.GetEnvironmentVariable("PUBLICACAO_TEST_FBCLIENT"),
            UserID = "SYSDBA", Password = "masterkey", Charset = "UTF8", Pooling = false
        }.ToString();
        FbConnection.CreateDatabase(cs, overwrite: false);
        return cs;
    }

    private static async Task Migrate(FbConnection connection, string file)
    {
        var root = new DirectoryInfo(AppContext.BaseDirectory);
        while (root is not null && !Directory.Exists(Path.Combine(root.FullName, "backend", "sql"))) root = root.Parent;
        var path = root is not null ? Path.Combine(root.FullName, "backend", "sql", file)
            : Path.Combine(Environment.GetEnvironmentVariable("PUBLICACAO_TEST_REPO")!, "backend", "sql", file);
        var script = new FbScript(await File.ReadAllTextAsync(path));
        script.Parse();
        foreach (var statement in script.Results)
            if (!statement.Text.Trim().Equals("COMMIT", StringComparison.OrdinalIgnoreCase)) await connection.ExecuteAsync(statement.Text);
    }

    public Task DisposeAsync()
    {
        if (sourceCs.Length > 0) FbConnection.DropDatabase(sourceCs);
        if (targetCs.Length > 0) FbConnection.DropDatabase(targetCs);
        return Task.CompletedTask;
    }
    private sealed class SourceFactory(string cs) : IFirebirdConnectionFactory
    {
        public async Task<FbConnection> OpenConnectionAsync(CancellationToken ct = default) { var c = new FbConnection(cs); await c.OpenAsync(ct); return c; }
    }
    private sealed class TargetFactory(string cs) : IAssistantFirebirdConnectionFactory
    {
        public async Task<FbConnection> OpenConnectionAsync(CancellationToken ct = default) { var c = new FbConnection(cs); await c.OpenAsync(ct); return c; }
    }
}
