-- Executar uma vez no banco CONTEUDOS que ja possui a publicacao inicial.
CREATE TABLE ASS_SCRIPT_MAPA (
 CODSCRIPTLAUDO INTEGER NOT NULL,
 CODESPECIALIDADE INTEGER NOT NULL,
 PRIMARY KEY (CODSCRIPTLAUDO, CODESPECIALIDADE)
);
SET TERM ^ ;
CREATE OR ALTER TRIGGER ASS_MAPA_EVENTO FOR ASS_PACOTE_MAPA ACTIVE AFTER INSERT OR DELETE POSITION 100 AS
DECLARE VARIABLE P INTEGER;
DECLARE VARIABLE S INTEGER;
BEGIN
 IF (DELETING) THEN P = OLD.CODPACOTE; ELSE P = NEW.CODPACOTE;
 FOR SELECT CODSCRIPTLAUDO FROM SCRIPTLAUDO
 WHERE CODPACOTE = :P
 AND NOT EXISTS (SELECT 1 FROM ASS_SCRIPT_MAPA M WHERE M.CODSCRIPTLAUDO = SCRIPTLAUDO.CODSCRIPTLAUDO)
 INTO :S DO
 EXECUTE PROCEDURE ASS_ENFILEIRAR(:S);
END^
CREATE OR ALTER TRIGGER ASS_SCRIPT_MAPA_EVENTO FOR ASS_SCRIPT_MAPA ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 100 AS
BEGIN
 IF (DELETING) THEN EXECUTE PROCEDURE ASS_ENFILEIRAR(OLD.CODSCRIPTLAUDO);
 ELSE EXECUTE PROCEDURE ASS_ENFILEIRAR(NEW.CODSCRIPTLAUDO);
END^
SET TERM ; ^
COMMIT;
