-- Executar uma vez no banco ASSISTENTE. Nao executar no banco Conteudos.
CREATE TABLE CON_PUBLICACAO (
 ORIGEM VARCHAR(64) NOT NULL,
 CODORIGEM INTEGER NOT NULL,
 CODDESTINO INTEGER,
 CODMRD INTEGER,
 REVISAO BIGINT DEFAULT 0 NOT NULL,
 CODVERSAO INTEGER,
 SUSPENSO SMALLINT DEFAULT 0 NOT NULL,
 BLOQUEADO SMALLINT DEFAULT 0 NOT NULL,
 INATIVO_ORIGEM SMALLINT DEFAULT 0 NOT NULL,
 PRIMARY KEY (ORIGEM, CODORIGEM),
 UNIQUE (CODDESTINO)
);
CREATE TABLE CON_PUBLICACAO_ESP (
 ORIGEM VARCHAR(64) NOT NULL,
 CODORIGEM INTEGER NOT NULL,
 CODESPECIALIDADE INTEGER NOT NULL,
 PRIMARY KEY (ORIGEM, CODORIGEM, CODESPECIALIDADE)
);
CREATE EXCEPTION CON_EDICAO 'Edite o modelo sincronizado em Conteudos.';
CREATE TABLE CON_PUBLICACAO_MRD_ESP (
 ORIGEM VARCHAR(64) NOT NULL,
 CODORIGEM INTEGER NOT NULL,
 CODESPECIALIDADE INTEGER NOT NULL,
 PRIMARY KEY (ORIGEM, CODORIGEM, CODESPECIALIDADE)
);
CREATE EXCEPTION CON_INATIVO 'O modelo esta inativo na origem.';
SET TERM ^ ;
CREATE TRIGGER CON_SCRIPT_GUARDA FOR SCRIPTLAUDO ACTIVE BEFORE UPDATE POSITION 0 AS
DECLARE VARIABLE S INTEGER;
BEGIN
 IF (RDB$GET_CONTEXT('USER_TRANSACTION', 'PUBLICACAO') IS DISTINCT FROM '1') THEN
 BEGIN
  SELECT INATIVO_ORIGEM FROM CON_PUBLICACAO WHERE CODDESTINO = OLD.CODSCRIPTLAUDO INTO :S;
  IF (S IS NOT NULL) THEN
  BEGIN
   IF (NEW.TITULO IS DISTINCT FROM OLD.TITULO OR NEW.TIPOSCRIPT IS DISTINCT FROM OLD.TIPOSCRIPT
       OR NEW.ESTRUTURASCRIPT IS DISTINCT FROM OLD.ESTRUTURASCRIPT) THEN EXCEPTION CON_EDICAO;
   IF (S = 1 AND NEW.STATUS <> 0) THEN EXCEPTION CON_INATIVO;
   IF (NEW.STATUS IS DISTINCT FROM OLD.STATUS) THEN
    UPDATE CON_PUBLICACAO SET BLOQUEADO = IIF(NEW.STATUS = 0, 1, 0) WHERE CODDESTINO = OLD.CODSCRIPTLAUDO;
  END
 END
END^
CREATE TRIGGER CON_SCRIPT_EXCLUSAO FOR SCRIPTLAUDO ACTIVE BEFORE DELETE POSITION 0 AS
BEGIN
 UPDATE CON_PUBLICACAO SET SUSPENSO = 1, CODDESTINO = NULL WHERE CODDESTINO = OLD.CODSCRIPTLAUDO;
END^
SET TERM ; ^
COMMIT;
