-- Executar uma vez no banco CONTEUDOS, com isql (SET TERM).
CREATE SEQUENCE GEN_ASS_PUBLICACAO;
CREATE TABLE ASS_PACOTE_MAPA (
 CODPACOTE INTEGER NOT NULL,
 CODESPECIALIDADE INTEGER NOT NULL,
 PRIMARY KEY (CODPACOTE, CODESPECIALIDADE)
);
CREATE TABLE ASS_PUBLICACAO (
 CODSCRIPTLAUDO INTEGER NOT NULL PRIMARY KEY,
 REVISAO BIGINT NOT NULL,
 ESTADO VARCHAR(20) DEFAULT 'pendente' NOT NULL,
 TENTATIVAS INTEGER DEFAULT 0 NOT NULL,
 PROXIMA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 PUBLICADO_EM TIMESTAMP,
 CODDESTINO INTEGER,
 ERRO VARCHAR(1000)
);
SET TERM ^ ;
CREATE PROCEDURE ASS_ENFILEIRAR (ID INTEGER) AS
BEGIN
 IF (ID IS NOT NULL) THEN
 UPDATE OR INSERT INTO ASS_PUBLICACAO
 (CODSCRIPTLAUDO, REVISAO, ESTADO, TENTATIVAS, PROXIMA, ERRO)
 VALUES (:ID, NEXT VALUE FOR GEN_ASS_PUBLICACAO, 'pendente', 0, CURRENT_TIMESTAMP, NULL)
 MATCHING (CODSCRIPTLAUDO);
END^
CREATE TRIGGER ASS_SCRIPT_EVENTO FOR SCRIPTLAUDO ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 100 AS
BEGIN
 IF (DELETING) THEN EXECUTE PROCEDURE ASS_ENFILEIRAR(OLD.CODSCRIPTLAUDO);
 ELSE EXECUTE PROCEDURE ASS_ENFILEIRAR(NEW.CODSCRIPTLAUDO);
END^
CREATE TRIGGER ASS_VERSAO_EVENTO FOR SCRIPTVERSOES ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 100 AS
BEGIN
 IF (DELETING) THEN EXECUTE PROCEDURE ASS_ENFILEIRAR(OLD.CODSCRIPTLAUDO);
 ELSE EXECUTE PROCEDURE ASS_ENFILEIRAR(NEW.CODSCRIPTLAUDO);
END^
CREATE TRIGGER ASS_MRD_EVENTO FOR SCRIPTLAUDOMRD ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 100 AS
BEGIN
 IF (DELETING) THEN EXECUTE PROCEDURE ASS_ENFILEIRAR(OLD.CODSCRIPTLAUDO);
 ELSE EXECUTE PROCEDURE ASS_ENFILEIRAR(NEW.CODSCRIPTLAUDO);
END^
CREATE TRIGGER ASS_VM_EVENTO FOR SCRIPTVERSAOMRD ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 100 AS
DECLARE VARIABLE V INTEGER;
DECLARE VARIABLE S INTEGER;
BEGIN
 IF (DELETING) THEN V = OLD.CODVERSAO; ELSE V = NEW.CODVERSAO;
 SELECT CODSCRIPTLAUDO FROM SCRIPTVERSOES WHERE CODVERSAO = :V INTO :S;
 EXECUTE PROCEDURE ASS_ENFILEIRAR(:S);
END^
CREATE TRIGGER ASS_MAPA_EVENTO FOR ASS_PACOTE_MAPA ACTIVE AFTER INSERT OR DELETE POSITION 100 AS
DECLARE VARIABLE P INTEGER;
DECLARE VARIABLE S INTEGER;
BEGIN
 IF (DELETING) THEN P = OLD.CODPACOTE; ELSE P = NEW.CODPACOTE;
 FOR SELECT CODSCRIPTLAUDO FROM SCRIPTLAUDO WHERE CODPACOTE = :P INTO :S DO
 EXECUTE PROCEDURE ASS_ENFILEIRAR(:S);
END^
SET TERM ; ^
COMMIT;
