/* Comentario por idade — DDL + migracao ASE 2025 (COD 795) Tabela 5
   NAO apaga faixas NORMALIDADE existentes.
   Bandas novas/ajustadas: 20-39, 40-59, 60-80 (idade 60 sem sobreposicao).
   Execute contra bd/REFERENCIAS.FDB
*/

/* --- DDL NORMALIDADECOMENTARIO --- */
ALTER TABLE NORMALIDADECOMENTARIO ADD IDADE_MIN SMALLINT DEFAULT -1;
COMMIT;
ALTER TABLE NORMALIDADECOMENTARIO ADD IDADE_MAX SMALLINT DEFAULT -1;
COMMIT;
UPDATE NORMALIDADECOMENTARIO SET IDADE_MIN = -1 WHERE IDADE_MIN IS NULL;
UPDATE NORMALIDADECOMENTARIO SET IDADE_MAX = -1 WHERE IDADE_MAX IS NULL;
COMMIT;
ALTER TABLE NORMALIDADECOMENTARIO ALTER COLUMN IDADE_MIN SET NOT NULL;
ALTER TABLE NORMALIDADECOMENTARIO ALTER COLUMN IDADE_MAX SET NOT NULL;
COMMIT;

ALTER TABLE NORMALIDADECOMENTARIO DROP CONSTRAINT UQ_NORMALIDADECOMENTARIO_VAR_REF_SEXO;
COMMIT;
ALTER TABLE NORMALIDADECOMENTARIO ADD CONSTRAINT UQ_NORMALIDADECOMENTARIO_VAR_REF_SEXO_IDADE
  UNIQUE (CODVARIAVEL, CODREFERENCIA, SEXO, IDADE_MIN, IDADE_MAX);
COMMIT;

/* --- DDL PADRAONORMALIDADECOMENTARIO --- */
ALTER TABLE PADRAONORMALIDADECOMENTARIO ADD IDADE_MIN SMALLINT DEFAULT -1;
COMMIT;
ALTER TABLE PADRAONORMALIDADECOMENTARIO ADD IDADE_MAX SMALLINT DEFAULT -1;
COMMIT;
UPDATE PADRAONORMALIDADECOMENTARIO SET IDADE_MIN = -1 WHERE IDADE_MIN IS NULL;
UPDATE PADRAONORMALIDADECOMENTARIO SET IDADE_MAX = -1 WHERE IDADE_MAX IS NULL;
COMMIT;
ALTER TABLE PADRAONORMALIDADECOMENTARIO ALTER COLUMN IDADE_MIN SET NOT NULL;
ALTER TABLE PADRAONORMALIDADECOMENTARIO ALTER COLUMN IDADE_MAX SET NOT NULL;
COMMIT;

ALTER TABLE PADRAONORMALIDADECOMENTARIO DROP CONSTRAINT UQ_PADRAOCOM_PADRAO_VAR_SEXO;
COMMIT;
ALTER TABLE PADRAONORMALIDADECOMENTARIO ADD CONSTRAINT UQ_PADRAOCOM_PADRAO_VAR_SEXO_IDADE
  UNIQUE (CODPADRAO, CODVARIAVEL, SEXO, IDADE_MIN, IDADE_MAX);
COMMIT;

/* Normalizar banda do meio ja existente (E/A): 40-60 -> 40-59 — nao apaga */
UPDATE NORMALIDADE SET IDADE_MAX = 59
WHERE CODREFERENCIA = 795 AND CODVARIAVEL IN (210, 211)
  AND IDADE_MIN = 40 AND IDADE_MAX = 60;
COMMIT;

/* Inserir faixas por idade ausentes (Tabela 5) — nao remove legadas */
/* E/A ratio 236 */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (236,795,1,0.88,2.73,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (236,795,1,0.69,2.07,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (236,795,1,0.50,1.40,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

/* e' lateral 214 */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (214,795,1,9.9,22.1,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (214,795,1,7.5,17.5,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (214,795,1,5.2,13.0,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

/* e' septal 213 */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (213,795,1,7.2,16.4,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (213,795,1,5.7,13.5,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (213,795,1,4.1,10.6,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

/* e' media 243 */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (243,795,1,8.7,19.1,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (243,795,1,6.7,15.4,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (243,795,1,4.7,11.7,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

/* E/e' lateral 253 */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (253,795,1,2.5,6.3,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (253,795,1,3.6,9.4,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (253,795,1,4.8,12.6,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

/* E/e' septal 244 */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (244,795,1,4.0,9.1,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (244,795,1,4.9,12.1,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (244,795,1,5.9,15.2,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

/* E/e' medio 104 */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (104,795,1,4.0,9.1,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (104,795,1,4.6,11.5,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (104,795,1,5.2,14.0,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

/* TR velocity 129 */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (129,795,1,1.3,2.7,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (129,795,1,1.5,2.7,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (129,795,1,1.7,2.8,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

/* LARS / SAER 164 — LA strain geral (nao vendor) */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (164,795,1,29.5,63.2,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (164,795,1,26.8,57.7,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (164,795,1,24.1,52.3,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

/* LAVi geral -> VR_VOL_AE_INDEX 251 (metodo combinado Tabela 5) */
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (251,795,1,12.1,39.4,'A',20,39,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (251,795,1,12.9,38.3,'A',40,59,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADE (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,VALORMIN,VALORMAX,SEXO,IDADE_MIN,IDADE_MAX,PAGINA_REFERENCIA,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (251,795,1,13.7,37.1,'A',60,80,551,38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,CODCLASSIFICACAO,SEXO,IDADE_MIN,IDADE_MAX);

COMMIT;

/* Comentarios por idade (SEXO=A). Mantem comentarios legados com IDADE -1/-1. */
/* E onda cm/s (como faixas ja gravadas) */
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (210,795,'A',20,39,'54-111',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (210,795,'A',40,59,'47-102',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (210,795,'A',60,80,'39-92',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (211,795,'A',20,39,'24-68',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (211,795,'A',40,59,'33-82',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (211,795,'A',60,80,'43-97',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (236,795,'A',20,39,'0.88-2.73',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (236,795,'A',40,59,'0.69-2.07',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (236,795,'A',60,80,'0.50-1.40',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (214,795,'A',20,39,'9.9-22.1',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (214,795,'A',40,59,'7.5-17.5',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (214,795,'A',60,80,'5.2-13.0',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (213,795,'A',20,39,'7.2-16.4',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (213,795,'A',40,59,'5.7-13.5',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (213,795,'A',60,80,'4.1-10.6',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (243,795,'A',20,39,'8.7-19.1',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (243,795,'A',40,59,'6.7-15.4',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (243,795,'A',60,80,'4.7-11.7',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (253,795,'A',20,39,'2.5-6.3',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (253,795,'A',40,59,'3.6-9.4',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (253,795,'A',60,80,'4.8-12.6',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (244,795,'A',20,39,'4.0-9.1',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (244,795,'A',40,59,'4.9-12.1',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (244,795,'A',60,80,'5.9-15.2',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (104,795,'A',20,39,'4.0-9.1',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (104,795,'A',40,59,'4.6-11.5',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (104,795,'A',60,80,'5.2-14.0',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (129,795,'A',20,39,'1.3-2.7',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (129,795,'A',40,59,'1.5-2.7',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (129,795,'A',60,80,'1.7-2.8',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (164,795,'A',20,39,'29.5-63.2',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (164,795,'A',40,59,'26.8-57.7',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (164,795,'A',60,80,'24.1-52.3',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (251,795,'A',20,39,'12.1-39.4',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (251,795,'A',40,59,'12.9-38.3',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (251,795,'A',60,80,'13.7-37.1',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO,IDADE_MIN,IDADE_MAX);

COMMIT;
