/* Comentario por sexo — DDL + migracao ESC 2024 */
/* Execute com isql -i contra bd/REFERENCIAS.FDB */

ALTER TABLE NORMALIDADECOMENTARIO ADD SEXO CHAR(1) DEFAULT 'A';
COMMIT;

UPDATE NORMALIDADECOMENTARIO SET SEXO = 'A' WHERE SEXO IS NULL;
COMMIT;

ALTER TABLE NORMALIDADECOMENTARIO ALTER COLUMN SEXO SET NOT NULL;
COMMIT;

ALTER TABLE NORMALIDADECOMENTARIO DROP CONSTRAINT UQ_NORMALIDADECOMENTARIO_VAR_REF;
COMMIT;

ALTER TABLE NORMALIDADECOMENTARIO ADD CONSTRAINT UQ_NORMALIDADECOMENTARIO_VAR_REF_SEXO UNIQUE (CODVARIAVEL, CODREFERENCIA, SEXO);
COMMIT;

ALTER TABLE PADRAONORMALIDADECOMENTARIO ADD SEXO CHAR(1) DEFAULT 'A';
COMMIT;

UPDATE PADRAONORMALIDADECOMENTARIO SET SEXO = 'A' WHERE SEXO IS NULL;
COMMIT;

ALTER TABLE PADRAONORMALIDADECOMENTARIO ALTER COLUMN SEXO SET NOT NULL;
COMMIT;

ALTER TABLE PADRAONORMALIDADECOMENTARIO DROP CONSTRAINT UQ_PADRAOCOM_PADRAO_VAR;
COMMIT;

ALTER TABLE PADRAONORMALIDADECOMENTARIO ADD CONSTRAINT UQ_PADRAOCOM_PADRAO_VAR_SEXO UNIQUE (CODPADRAO, CODVARIAVEL, SEXO);
COMMIT;

/* Migrar aortas ESC 2024 (COD 796) */
DELETE FROM NORMALIDADECOMENTARIO WHERE CODVARIAVEL=192 AND CODREFERENCIA=796;
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (192,796,'F','<= 36',38,CURRENT_TIMESTAMP);
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (192,796,'M','<= 40',38,CURRENT_TIMESTAMP);

DELETE FROM NORMALIDADECOMENTARIO WHERE CODVARIAVEL=80 AND CODREFERENCIA=796;
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (80,796,'F','<= 36',38,CURRENT_TIMESTAMP);
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (80,796,'M','<= 40',38,CURRENT_TIMESTAMP);

DELETE FROM NORMALIDADECOMENTARIO WHERE CODVARIAVEL=82 AND CODREFERENCIA=796;
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (82,796,'F','<= 33',38,CURRENT_TIMESTAMP);
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (82,796,'M','<= 38',38,CURRENT_TIMESTAMP);

DELETE FROM NORMALIDADECOMENTARIO WHERE CODVARIAVEL=235 AND CODREFERENCIA=796;
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (235,796,'F','<= 34',38,CURRENT_TIMESTAMP);
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (235,796,'M','<= 40',38,CURRENT_TIMESTAMP);

DELETE FROM NORMALIDADECOMENTARIO WHERE CODVARIAVEL=86 AND CODREFERENCIA=796;
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (86,796,'F','<= 34',38,CURRENT_TIMESTAMP);
INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (86,796,'M','<= 37',38,CURRENT_TIMESTAMP);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,SEXO,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO)
VALUES (84,796,'A','< 22',38,CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL,CODREFERENCIA,SEXO);

COMMIT;
