/* Limpeza ESC 2024 (COD 796): remove graus operacionais sem respaldo na Figura 5. */
/* Mantem apenas Normal (CODCLASSIFICACAO=1) + comentario de limiar. */

DELETE FROM NORMALIDADE
WHERE CODREFERENCIA = 796
  AND CODCLASSIFICACAO IN (2, 3, 4);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL, CODREFERENCIA, TEXTO, CODUSUARIO, DTHRULTMODIFICACAO)
VALUES (192, 796, 'F <= 36; M <= 40', 38, CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL, CODREFERENCIA);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL, CODREFERENCIA, TEXTO, CODUSUARIO, DTHRULTMODIFICACAO)
VALUES (80, 796, 'F <= 36; M <= 40', 38, CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL, CODREFERENCIA);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL, CODREFERENCIA, TEXTO, CODUSUARIO, DTHRULTMODIFICACAO)
VALUES (82, 796, 'F <= 33; M <= 38', 38, CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL, CODREFERENCIA);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL, CODREFERENCIA, TEXTO, CODUSUARIO, DTHRULTMODIFICACAO)
VALUES (235, 796, 'F <= 34; M <= 40', 38, CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL, CODREFERENCIA);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL, CODREFERENCIA, TEXTO, CODUSUARIO, DTHRULTMODIFICACAO)
VALUES (84, 796, '< 22', 38, CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL, CODREFERENCIA);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL, CODREFERENCIA, TEXTO, CODUSUARIO, DTHRULTMODIFICACAO)
VALUES (86, 796, 'F <= 34; M <= 37', 38, CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL, CODREFERENCIA);

COMMIT;
