/* Limpeza idempotente: referencias sem normalidade vinculada */
/* Execute em bd/REFERENCIAS.FDB */

UPDATE EQUACOESLINGUAGEM SET CODREFERENCIA = NULL
WHERE CODREFERENCIA IN (
  SELECT r.CODREFERENCIA FROM REFERENCIA r
  WHERE NOT EXISTS (
    SELECT 1 FROM NORMALIDADE n WHERE n.CODREFERENCIA = r.CODREFERENCIA
  )
);

DELETE FROM REFERENCIA_AUTORES
WHERE CODREFERENCIA IN (
  SELECT r.CODREFERENCIA FROM REFERENCIA r
  WHERE NOT EXISTS (
    SELECT 1 FROM NORMALIDADE n WHERE n.CODREFERENCIA = r.CODREFERENCIA
  )
);

DELETE FROM ANEXOS
WHERE CODREFERENCIA IN (
  SELECT r.CODREFERENCIA FROM REFERENCIA r
  WHERE NOT EXISTS (
    SELECT 1 FROM NORMALIDADE n WHERE n.CODREFERENCIA = r.CODREFERENCIA
  )
);

DELETE FROM NORMALIDADECOMENTARIO
WHERE CODREFERENCIA IN (
  SELECT r.CODREFERENCIA FROM REFERENCIA r
  WHERE NOT EXISTS (
    SELECT 1 FROM NORMALIDADE n WHERE n.CODREFERENCIA = r.CODREFERENCIA
  )
);

DELETE FROM REFERENCIA r
WHERE NOT EXISTS (
  SELECT 1 FROM NORMALIDADE n WHERE n.CODREFERENCIA = r.CODREFERENCIA
);

COMMIT;
