/* Medidas sem grau (binarias): remove Grave inventado; grava comentario do limiar */

/* Remove class Grave apenas quando nao existem leve/moderado na mesma var+ref */
DELETE FROM NORMALIDADE n
WHERE n.CODREFERENCIA IN (741,742,747,758,784,785,790)
  AND n.CODCLASSIFICACAO = 4
  AND NOT EXISTS (
    SELECT 1 FROM NORMALIDADE x
    WHERE x.CODVARIAVEL = n.CODVARIAVEL
      AND x.CODREFERENCIA = n.CODREFERENCIA
      AND x.CODCLASSIFICACAO IN (2, 3)
  );

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (97,1,'> 35',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (190,1,'> 0.095',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (161,1,'> 17',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (214,741,'> 10',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (213,741,'> 7',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (104,741,'<= 14',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (236,741,'0.8-2',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (253,741,'<= 13',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (244,741,'<= 15',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (198,741,'160-240',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (43,741,'<= 34',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (129,741,'<= 2.8',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (251,741,'<= 34',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (154,742,'<= -18',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (214,747,'> 10',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (213,747,'> 8',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (104,747,'<= 15',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (251,747,'<= 34',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (154,758,'<= -18',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (154,784,'<= -18',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (245,784,'<= -20',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (154,785,'<= -18',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (245,785,'<= -20',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (97,790,'> 35',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (100,790,'<= -20',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (190,790,'> 9.5',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);
UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (CODVARIAVEL,CODREFERENCIA,TEXTO,CODUSUARIO,DTHRULTMODIFICACAO) VALUES (161,790,'> 17',38,CURRENT_TIMESTAMP) MATCHING (CODVARIAVEL,CODREFERENCIA);

COMMIT;
