/* Medidas do JSON ainda sem NORMALIDADE — somente com fonte primaria confirmada. */
/* VR_ERP / CODVARIAVEL=95 — ASE Chamber Quantification 2015, Tabela 6 e Figura 6, p.17 */
/* CODREFERENCIA=1 ja existe no banco. Idempotente. */

INSERT INTO NORMALIDADE (
  CODVARIAVEL, CODREFERENCIA, CODCLASSIFICACAO,
  VALORMIN, VALORMAX, SEXO, IDADE_MIN, IDADE_MAX,
  PAGINA_REFERENCIA, CODUSUARIO, DTHRULTMODIFICACAO
)
SELECT 95, 1, 1, 0.22, 0.42, 'F', NULL, NULL, 17, 38, CURRENT_TIMESTAMP
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM NORMALIDADE n
  WHERE n.CODVARIAVEL = 95 AND n.CODREFERENCIA = 1
    AND n.SEXO = 'F' AND n.CODCLASSIFICACAO = 1
);

INSERT INTO NORMALIDADE (
  CODVARIAVEL, CODREFERENCIA, CODCLASSIFICACAO,
  VALORMIN, VALORMAX, SEXO, IDADE_MIN, IDADE_MAX,
  PAGINA_REFERENCIA, CODUSUARIO, DTHRULTMODIFICACAO
)
SELECT 95, 1, 1, 0.24, 0.42, 'M', NULL, NULL, 17, 38, CURRENT_TIMESTAMP
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM NORMALIDADE n
  WHERE n.CODVARIAVEL = 95 AND n.CODREFERENCIA = 1
    AND n.SEXO = 'M' AND n.CODCLASSIFICACAO = 1
);

UPDATE OR INSERT INTO NORMALIDADECOMENTARIO (
  CODVARIAVEL, CODREFERENCIA, TEXTO, CODUSUARIO, DTHRULTMODIFICACAO
) VALUES (95, 1, '<= 0,42', 38, CURRENT_TIMESTAMP)
MATCHING (CODVARIAVEL, CODREFERENCIA);

COMMIT;
