/* Job ASE 2025 — converter legados Onda E/A (210/211) de m/s → cm/s
   - Atualiza VARIAVEIS.CODUNIDADEMEDIDA para cm/s (COD 8)
   - Converte só faixas SEM idade com VALORMAX <= 5 (legado m/s)
   - Converte só comentários com IDADE -1/-1 e padrão numérico pequeno (0.x)
   - NÃO toca faixas/comentários etários já em cm/s (54-111 etc.)
   Idempotente se valores já >= 10 (já destino).
   Execute contra bd/REFERENCIAS.FDB
*/

/* 1) Unidade da variável → cm/s */
UPDATE VARIAVEIS SET CODUNIDADEMEDIDA = 8, CODUSUARIO = 38, DTHRULTMODIFICACAO = CURRENT_TIMESTAMP
WHERE CODVARIAVEL IN (210, 211)
  AND (CODUNIDADEMEDIDA IS DISTINCT FROM 8);
COMMIT;

/* 2) Faixas NORMALIDADE sem idade, magnitude m/s (VALORMAX <= 5), COD 795 */
UPDATE NORMALIDADE
SET VALORMIN = VALORMIN * 100,
    VALORMAX = VALORMAX * 100,
    CODUSUARIO = 38,
    DTHRULTMODIFICACAO = CURRENT_TIMESTAMP
WHERE CODREFERENCIA = 795
  AND CODVARIAVEL IN (210, 211)
  AND IDADE_MIN IS NULL
  AND IDADE_MAX IS NULL
  AND VALORMAX IS NOT NULL
  AND VALORMAX <= 5
  AND VALORMAX <> 999
  AND VALORMAX <> -999;
COMMIT;

/* 3) Comentários gerais legados (IDADE -1/-1) — padrões conhecidos E/A */
UPDATE NORMALIDADECOMENTARIO SET TEXTO = '80 +/- 20', CODUSUARIO = 38, DTHRULTMODIFICACAO = CURRENT_TIMESTAMP
WHERE CODVARIAVEL = 210 AND CODREFERENCIA = 795 AND SEXO = 'A' AND IDADE_MIN = -1 AND IDADE_MAX = -1
  AND (TEXTO = '0.8 +/- 0.2' OR TEXTO = '0.8 ± 0.2' OR TEXTO = '0.8+/-0.2');

UPDATE NORMALIDADECOMENTARIO SET TEXTO = '50 +/- 20', CODUSUARIO = 38, DTHRULTMODIFICACAO = CURRENT_TIMESTAMP
WHERE CODVARIAVEL = 211 AND CODREFERENCIA = 795 AND SEXO = 'A' AND IDADE_MIN = -1 AND IDADE_MAX = -1
  AND (TEXTO = '0.5 +/- 0.2' OR TEXTO = '0.5 ± 0.2' OR TEXTO = '0.5+/-0.2');

UPDATE NORMALIDADECOMENTARIO SET TEXTO = '60-100', CODUSUARIO = 38, DTHRULTMODIFICACAO = CURRENT_TIMESTAMP
WHERE CODVARIAVEL = 210 AND CODREFERENCIA = 795 AND SEXO = 'A' AND IDADE_MIN = -1 AND IDADE_MAX = -1
  AND (TEXTO = '0.6-1' OR TEXTO = '0.6 - 1');

UPDATE NORMALIDADECOMENTARIO SET TEXTO = '20-50', CODUSUARIO = 38, DTHRULTMODIFICACAO = CURRENT_TIMESTAMP
WHERE CODVARIAVEL = 211 AND CODREFERENCIA = 795 AND SEXO = 'A' AND IDADE_MIN = -1 AND IDADE_MAX = -1
  AND (TEXTO = '0.2-0.5' OR TEXTO = '0.2 - 0.5');

COMMIT;
