SET AUTODDL ON;

-- =============================================================================
-- Migração de nomes de tabelas (REFERENCIAS.FDB / Firebird 5)
-- Regra: "_" somente em tabelas de relacionamento (N:N).
-- Entidades/satélites passam a nome composto sem underline.
-- PK de entidade: coluna com prefixo COD* (nunca ID genérico).
--
-- Pré-requisito: rename-integ-constraints.sql já aplicado (PK/FK/UNIQUE OK).
-- Firebird NÃO tem RENAME TABLE: recria tabela, copia dados, recria FKs.
--
-- FAÇA BACKUP antes. NÃO é idempotente. Rode com o app parado.
-- Depois atualize o backend para os novos nomes.
-- =============================================================================

-- Mapeamento:
--   SCRIPT_VERSAO_ARQUIVOS -> SCRIPTVERSAOARQUIVOS
--   SCRIPT_VERSAO_HISTORICO -> SCRIPTVERSAOHISTORICO
--   SCRIPT_VERSAO_MRD -> SCRIPTVERSAOMRD
--   SCRIPT_APROVACAO_TOKEN -> SCRIPTAPROVACAOTOKEN
--   SCRIPT_ARQUIVOS -> SCRIPTARQUIVOS
--   SCRIPT_VERSOES -> SCRIPTVERSOES
--   SCRIPTLAUDO_MRD -> SCRIPTLAUDOMRD
--   VARIAVEIS_NOMES_CLINICOS -> VARIAVEISNOMESCLINICOS
--   VARIAVEIS_ALTERNATIVAS -> VARIAVEISALTERNATIVAS
--   VARIAVEL_INDEXADA -> VARIAVELINDEXADA
--   RELATORIO_VALIDACOES -> RELATORIOVALIDACOES
--   RELATORIO_COLUNAS -> RELATORIOCOLUNAS
--   RELATORIO_FILTROS -> RELATORIOFILTROS
--   ECOCARDIOGRAFIA_ANALISES -> ECOCARDIOGRAFIAANALISES
--   CONFIGURACOES_SISTEMA -> CONFIGURACOESSISTEMA
--   POPULACAO_REFERENCIA -> POPULACAOREFERENCIA
--   GRUPOS_CLASSIFICACOES -> GRUPOSCLASSIFICACOES
--   MAPEAMENTO_VARIAVEL -> MAPEAMENTOVARIAVEL
--   EQUACOES_LINGUAGEM -> EQUACOESLINGUAGEM
--   MODELOS_MENSAGENS -> MODELOSMENSAGENS
--   GRUPOS_MENSAGENS -> GRUPOSMENSAGENS
--   GRUPOS_VARIAVEIS -> GRUPOSVARIAVEIS
--   SECAO_MODO_TEXTO -> SECAOMODOTEXTO
--   MODELO_MODO_TEXTO -> MODELOMODOTEXTO
--   CODIGO_UNIVERSAL -> CODIGOUNIVERSAL
--   MODULO_RELATORIO -> MODULORELATORIO
--   METODO_ANALISE -> METODOANALISE
--   MODO_AQUISICAO -> MODOAQUISICAO
--   TIPO_REFERENCIA -> TIPOREFERENCIA
--   IMPRESSO_VBS -> IMPRESSOVBS
--   TIPO_AUTOR -> TIPOAUTOR

-- -----------------------------------------------------------------------------
-- 1) DROP FOREIGN KEYS envolvidas
-- -----------------------------------------------------------------------------
ALTER TABLE AUTORES DROP CONSTRAINT FK_TIPO_AUTOR;
ALTER TABLE CLASSIFICACOES DROP CONSTRAINT FK_CLASSIFICACOES_GRUPO;
ALTER TABLE CONFIGURACOES_SISTEMA DROP CONSTRAINT FK_CONFIGURACOES_USUARIO;
ALTER TABLE ECOCARDIOGRAFIA_ANALISES DROP CONSTRAINT FK_ECOCARDIOGRAFIA_USER;
ALTER TABLE EQUACOES_LINGUAGEM DROP CONSTRAINT FK_EQUACOES_LINGUAGEM_FORMULA;
ALTER TABLE EQUACOES_LINGUAGEM DROP CONSTRAINT FK_EQUACOES_LINGUAGEM_LINGUAGEM;
ALTER TABLE EQUACOES_LINGUAGEM DROP CONSTRAINT FK_EQUACOES_LINGUAGEM_REFERENCIA;
ALTER TABLE IMPRESSO_VBS DROP CONSTRAINT FK_IMPRESSO_VBS_IMPRESSO;
ALTER TABLE IMPRESSO_VBS DROP CONSTRAINT FK_IMPRESSO_VBS_USUARIO;
ALTER TABLE MAPEAMENTO_VARIAVEL DROP CONSTRAINT FK_CODIGO;
ALTER TABLE MAPEAMENTO_VARIAVEL DROP CONSTRAINT FK_FABRICANTE;
ALTER TABLE MAPEAMENTO_VARIAVEL DROP CONSTRAINT FK_VARIAVEL;
ALTER TABLE MODELOS_MENSAGENS DROP CONSTRAINT FK_MODELOS_MENSAGENS_GRUPO;
ALTER TABLE MODELO_MODO_TEXTO DROP CONSTRAINT MODELO_CODUSUARIO_FK;
ALTER TABLE MODULO_RELATORIO DROP CONSTRAINT FK_MODULO_REL_USUARIO_ATUALIZACAO;
ALTER TABLE MODULO_RELATORIO DROP CONSTRAINT FK_MODULO_REL_USUARIO_CRIACAO;
ALTER TABLE NORMALIDADE DROP CONSTRAINT FK_NORMALIDADE_MODO_AQUISICAO;
ALTER TABLE NORMALIDADE DROP CONSTRAINT FK_NORMALIDADE_POPULACAO;
ALTER TABLE REFERENCIA DROP CONSTRAINT FK_TIPOREF;
ALTER TABLE RELATORIOS DROP CONSTRAINT FK_RELATORIO_MODULO;
ALTER TABLE RELATORIO_COLUNAS DROP CONSTRAINT FK_RELATORIO_COLUNAS_RELATORIOS;
ALTER TABLE RELATORIO_FILTROS DROP CONSTRAINT FK_RELATORIO_FILTROS_USUARIO_A;
ALTER TABLE RELATORIO_FILTROS DROP CONSTRAINT FK_RELATORIO_FILTROS_USUARIO_C;
ALTER TABLE RELATORIO_VALIDACOES DROP CONSTRAINT FK_VALIDACOES_RELATORIO;
ALTER TABLE RELATORIO_VALIDACOES DROP CONSTRAINT FK_VALIDACOES_USUARIO;
ALTER TABLE SCRIPTLAUDO_MRD DROP CONSTRAINT FK_SCRIPT_MRD_SCRIPT;
ALTER TABLE SCRIPT_APROVACAO_TOKEN DROP CONSTRAINT FK_SCRIPT_APROVACAO_TOKEN_SCRIPT;
ALTER TABLE SCRIPT_ARQUIVOS DROP CONSTRAINT FK_SCRIPT_ARQUIVOS_CODSCRIPTLAUDO;
ALTER TABLE SCRIPT_VERSAO_ARQUIVOS DROP CONSTRAINT FK_SCRIPT_VERSAO_ARQUIVOS_VERSAO;
ALTER TABLE SCRIPT_VERSAO_HISTORICO DROP CONSTRAINT FK_SCRIPT_VERSAO_HISTORICO_DESTINO;
ALTER TABLE SCRIPT_VERSAO_HISTORICO DROP CONSTRAINT FK_SCRIPT_VERSAO_HISTORICO_ORIGEM;
ALTER TABLE SCRIPT_VERSAO_MRD DROP CONSTRAINT FK_VERSAO_MRD_VERSAO;
ALTER TABLE SCRIPT_VERSOES DROP CONSTRAINT FK_SCRIPT_VERSOES_SCRIPT;
ALTER TABLE SECAO_MODO_TEXTO DROP CONSTRAINT SECAO_CODMODELO_FK;
ALTER TABLE SECAO_VARIAVEL DROP CONSTRAINT SECAO_VARIAVEL_CODSECAO_FK;
ALTER TABLE SISTEMA_MODULO DROP CONSTRAINT FK_SISMOD_MODULO;
ALTER TABLE VARIAVEIS DROP CONSTRAINT FK_VARIAVEIS_GRUPO;
ALTER TABLE VARIAVEIS_ALTERNATIVAS DROP CONSTRAINT VARIAVEIS_ALTERNATIVAS_CODUSUARIO_FK;
ALTER TABLE VARIAVEIS_ALTERNATIVAS DROP CONSTRAINT VARIAVEIS_ALTERNATIVAS_FK;
ALTER TABLE VARIAVEIS_NOMES_CLINICOS DROP CONSTRAINT FK_VNC_CODVARIAVEL;
ALTER TABLE VARIAVEL_CODIGO_UNIVERSAL DROP CONSTRAINT FK_CODIGO_UNIVERSAL;
ALTER TABLE VARIAVEL_INDEXADA DROP CONSTRAINT VARIAVEL_INDEXADA_FK;
ALTER TABLE VARIAVEL_INDEXADA DROP CONSTRAINT VARIAVEL_UNIDADEMEDIDA_FK;
ALTER TABLE VARIAVEL_METODO DROP CONSTRAINT FK_METODO;
ALTER TABLE VARIAVEL_METODO DROP CONSTRAINT FK_MODO;

-- -----------------------------------------------------------------------------
-- 2) CREATE tabelas novas + INSERT + DROP antigas
-- -----------------------------------------------------------------------------

-- >>> TIPO_AUTOR -> TIPOAUTOR
CREATE TABLE TIPOAUTOR (
    CODTIPO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRICAO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_TIPOAUTOR PRIMARY KEY (CODTIPO)
);
INSERT INTO TIPOAUTOR (CODTIPO, DESCRICAO) SELECT CODTIPO, DESCRICAO FROM TIPO_AUTOR;
-- Ajuste o identity após conferir o MAX(CODTIPO):
-- ALTER TABLE TIPOAUTOR ALTER COLUMN CODTIPO RESTART WITH <MAX+1>;
DROP TABLE TIPO_AUTOR;

-- >>> TIPO_REFERENCIA -> TIPOREFERENCIA
CREATE TABLE TIPOREFERENCIA (
    CODTIPOREF INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(255),
    CONSTRAINT PK_TIPOREFERENCIA PRIMARY KEY (CODTIPOREF)
);
INSERT INTO TIPOREFERENCIA (CODTIPOREF, NOME, DESCRICAO) SELECT CODTIPOREF, NOME, DESCRICAO FROM TIPO_REFERENCIA;
-- Ajuste o identity após conferir o MAX(CODTIPOREF):
-- ALTER TABLE TIPOREFERENCIA ALTER COLUMN CODTIPOREF RESTART WITH <MAX+1>;
DROP TABLE TIPO_REFERENCIA;

-- >>> METODO_ANALISE -> METODOANALISE
CREATE TABLE METODOANALISE (
    CODMETODO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(255),
    SIGLA VARCHAR(10),
    CODUSUARIO INTEGER NOT NULL,
    OBSERVACAO VARCHAR(255),
    DTHRULTMODIFICACAO TIMESTAMP NOT NULL,
    CONSTRAINT PK_METODOANALISE PRIMARY KEY (CODMETODO),
    CONSTRAINT UNQ_METODOANALISE_NOME UNIQUE (NOME)
);
INSERT INTO METODOANALISE (CODMETODO, NOME, DESCRICAO, SIGLA, CODUSUARIO, OBSERVACAO, DTHRULTMODIFICACAO) SELECT CODMETODO, NOME, DESCRICAO, SIGLA, CODUSUARIO, OBSERVACAO, DTHRULTMODIFICACAO FROM METODO_ANALISE;
-- Ajuste o identity após conferir o MAX(CODMETODO):
-- ALTER TABLE METODOANALISE ALTER COLUMN CODMETODO RESTART WITH <MAX+1>;
DROP TABLE METODO_ANALISE;

-- >>> MODO_AQUISICAO -> MODOAQUISICAO
CREATE TABLE MODOAQUISICAO (
    CODMODO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(255),
    SIGLA VARCHAR(10),
    CONSTRAINT PK_MODOAQUISICAO PRIMARY KEY (CODMODO),
    CONSTRAINT UNQ_MODOAQUISICAO_NOME UNIQUE (NOME)
);
INSERT INTO MODOAQUISICAO (CODMODO, NOME, DESCRICAO, SIGLA) SELECT CODMODO, NOME, DESCRICAO, SIGLA FROM MODO_AQUISICAO;
-- Ajuste o identity após conferir o MAX(CODMODO):
-- ALTER TABLE MODOAQUISICAO ALTER COLUMN CODMODO RESTART WITH <MAX+1>;
DROP TABLE MODO_AQUISICAO;

-- >>> POPULACAO_REFERENCIA -> POPULACAOREFERENCIA
CREATE TABLE POPULACAOREFERENCIA (
    CODPOPULACAO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    ETNIA VARCHAR(50),
    CONDICAO_ESPECIAL VARCHAR(100),
    CONSTRAINT PK_POPULACAOREFERENCIA PRIMARY KEY (CODPOPULACAO)
);
INSERT INTO POPULACAOREFERENCIA (CODPOPULACAO, DESCRICAO, ETNIA, CONDICAO_ESPECIAL) SELECT CODPOPULACAO, DESCRICAO, ETNIA, CONDICAO_ESPECIAL FROM POPULACAO_REFERENCIA;
-- Ajuste o identity após conferir o MAX(CODPOPULACAO):
-- ALTER TABLE POPULACAOREFERENCIA ALTER COLUMN CODPOPULACAO RESTART WITH <MAX+1>;
DROP TABLE POPULACAO_REFERENCIA;

-- >>> CODIGO_UNIVERSAL -> CODIGOUNIVERSAL
CREATE TABLE CODIGOUNIVERSAL (
    COD_UNIVERSAL INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TIPO_CODIGO VARCHAR(20) NOT NULL,
    CODIGO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(255),
    UNIDADE VARCHAR(50),
    DESCRICAOPTBR VARCHAR(200),
    CONSTRAINT PK_CODIGOUNIVERSAL PRIMARY KEY (COD_UNIVERSAL)
);
INSERT INTO CODIGOUNIVERSAL (COD_UNIVERSAL, TIPO_CODIGO, CODIGO, DESCRICAO, UNIDADE, DESCRICAOPTBR) SELECT COD_UNIVERSAL, TIPO_CODIGO, CODIGO, DESCRICAO, UNIDADE, DESCRICAOPTBR FROM CODIGO_UNIVERSAL;
-- Ajuste o identity após conferir o MAX(COD_UNIVERSAL):
-- ALTER TABLE CODIGOUNIVERSAL ALTER COLUMN COD_UNIVERSAL RESTART WITH <MAX+1>;
DROP TABLE CODIGO_UNIVERSAL;

-- >>> GRUPOS_CLASSIFICACOES -> GRUPOSCLASSIFICACOES
CREATE TABLE GRUPOSCLASSIFICACOES (
    CODGRUPO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CODUSUARIO INTEGER NOT NULL,
    DTHRULTMODIFICACAO TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRUPOSCLASSIFICACOES PRIMARY KEY (CODGRUPO),
    CONSTRAINT UNQ_GRUPOSCLASSIFICACOES_NOME UNIQUE (NOME)
);
INSERT INTO GRUPOSCLASSIFICACOES (CODGRUPO, NOME, CODUSUARIO, DTHRULTMODIFICACAO) SELECT CODGRUPO, NOME, CODUSUARIO, DTHRULTMODIFICACAO FROM GRUPOS_CLASSIFICACOES;
-- Ajuste o identity após conferir o MAX(CODGRUPO):
-- ALTER TABLE GRUPOSCLASSIFICACOES ALTER COLUMN CODGRUPO RESTART WITH <MAX+1>;
DROP TABLE GRUPOS_CLASSIFICACOES;

-- >>> GRUPOS_MENSAGENS -> GRUPOSMENSAGENS
CREATE TABLE GRUPOSMENSAGENS (
    CODGRUPOMENSAGEM INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO BLOB SUB_TYPE 1,
    ATIVO SMALLINT NOT NULL,
    CODUSUARIO INTEGER NOT NULL,
    DTHRULTMODIFICACAO TIMESTAMP,
    CONSTRAINT PK_GRUPOSMENSAGENS PRIMARY KEY (CODGRUPOMENSAGEM)
);
INSERT INTO GRUPOSMENSAGENS (CODGRUPOMENSAGEM, NOME, DESCRICAO, ATIVO, CODUSUARIO, DTHRULTMODIFICACAO) SELECT CODGRUPOMENSAGEM, NOME, DESCRICAO, ATIVO, CODUSUARIO, DTHRULTMODIFICACAO FROM GRUPOS_MENSAGENS;
-- Ajuste o identity após conferir o MAX(CODGRUPOMENSAGEM):
-- ALTER TABLE GRUPOSMENSAGENS ALTER COLUMN CODGRUPOMENSAGEM RESTART WITH <MAX+1>;
DROP TABLE GRUPOS_MENSAGENS;

-- >>> GRUPOS_VARIAVEIS -> GRUPOSVARIAVEIS
CREATE TABLE GRUPOSVARIAVEIS (
    CODGRUPO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    ATIVO SMALLINT,
    DTHRULTMODIFICACAO TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRUPOSVARIAVEIS PRIMARY KEY (CODGRUPO)
);
INSERT INTO GRUPOSVARIAVEIS (CODGRUPO, NOME, DESCRICAO, ATIVO, DTHRULTMODIFICACAO) SELECT CODGRUPO, NOME, DESCRICAO, ATIVO, DTHRULTMODIFICACAO FROM GRUPOS_VARIAVEIS;
-- Ajuste o identity após conferir o MAX(CODGRUPO):
-- ALTER TABLE GRUPOSVARIAVEIS ALTER COLUMN CODGRUPO RESTART WITH <MAX+1>;
DROP TABLE GRUPOS_VARIAVEIS;

-- >>> CONFIGURACOES_SISTEMA -> CONFIGURACOESSISTEMA
-- PK: ID -> CODCONFIGSISTEMA (padrão COD*, alinhado a CODCONFIGAPI / CODCONFIGPOWERBI)
CREATE TABLE CONFIGURACOESSISTEMA (
    CODCONFIGSISTEMA INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CHAVE VARCHAR(100) NOT NULL,
    VALOR BLOB SUB_TYPE 1,
    CODUSUARIO INTEGER,
    DTHRULTMODIFICACAO TIMESTAMP,
    CONSTRAINT PK_CONFIGURACOESSISTEMA PRIMARY KEY (CODCONFIGSISTEMA)
);
INSERT INTO CONFIGURACOESSISTEMA (CODCONFIGSISTEMA, CHAVE, VALOR, CODUSUARIO, DTHRULTMODIFICACAO)
SELECT ID, CHAVE, VALOR, CODUSUARIO, DTHRULTMODIFICACAO FROM CONFIGURACOES_SISTEMA;
-- Ajuste o identity após conferir o MAX(CODCONFIGSISTEMA):
-- ALTER TABLE CONFIGURACOESSISTEMA ALTER COLUMN CODCONFIGSISTEMA RESTART WITH <MAX+1>;
DROP TABLE CONFIGURACOES_SISTEMA;

-- >>> ECOCARDIOGRAFIA_ANALISES -> ECOCARDIOGRAFIAANALISES
-- PK: ID -> CODANALISE (padrão COD*)
CREATE TABLE ECOCARDIOGRAFIAANALISES (
    CODANALISE INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    TEXTO_EXTRAIDO BLOB SUB_TYPE 1,
    RESULTADO_ANALISE BLOB SUB_TYPE 1,
    DATA_UPLOAD TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP,
    STATUS VARCHAR(50),
    CODUSUARIO INTEGER,
    CONSTRAINT PK_ECOCARDIOGRAFIAANALISES PRIMARY KEY (CODANALISE)
);
INSERT INTO ECOCARDIOGRAFIAANALISES (CODANALISE, NOME_ARQUIVO, TEXTO_EXTRAIDO, RESULTADO_ANALISE, DATA_UPLOAD, DATA_ATUALIZACAO, STATUS, CODUSUARIO)
SELECT ID, NOME_ARQUIVO, TEXTO_EXTRAIDO, RESULTADO_ANALISE, DATA_UPLOAD, DATA_ATUALIZACAO, STATUS, CODUSUARIO FROM ECOCARDIOGRAFIA_ANALISES;
-- Ajuste o identity após conferir o MAX(CODANALISE):
-- ALTER TABLE ECOCARDIOGRAFIAANALISES ALTER COLUMN CODANALISE RESTART WITH <MAX+1>;
DROP TABLE ECOCARDIOGRAFIA_ANALISES;

-- >>> MODULO_RELATORIO -> MODULORELATORIO
CREATE TABLE MODULORELATORIO (
    CODMODULO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(500),
    DTHRCRIACAO TIMESTAMP NOT NULL,
    DTHRATUALIZACAO TIMESTAMP NOT NULL,
    USUARIOCRIACAO INTEGER,
    USUARIOATUALIZACAO INTEGER,
    ATIVO SMALLINT,
    CONSTRAINT PK_MODULORELATORIO PRIMARY KEY (CODMODULO)
);
INSERT INTO MODULORELATORIO (CODMODULO, NOME, DESCRICAO, DTHRCRIACAO, DTHRATUALIZACAO, USUARIOCRIACAO, USUARIOATUALIZACAO, ATIVO) SELECT CODMODULO, NOME, DESCRICAO, DTHRCRIACAO, DTHRATUALIZACAO, USUARIOCRIACAO, USUARIOATUALIZACAO, ATIVO FROM MODULO_RELATORIO;
-- Ajuste o identity após conferir o MAX(CODMODULO):
-- ALTER TABLE MODULORELATORIO ALTER COLUMN CODMODULO RESTART WITH <MAX+1>;
DROP TABLE MODULO_RELATORIO;

-- >>> RELATORIO_FILTROS -> RELATORIOFILTROS
CREATE TABLE RELATORIOFILTROS (
    CODFILTRO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(400) NOT NULL,
    DESCRICAO VARCHAR(2000),
    TIPO VARCHAR(80) NOT NULL,
    SQL_FILTRO BLOB SUB_TYPE 1,
    SQL_QUERY BLOB SUB_TYPE 1,
    CATEGORIA VARCHAR(200),
    ORDEM INTEGER NOT NULL,
    OBRIGATORIO CHAR(1) NOT NULL,
    ATIVO CHAR(1) NOT NULL,
    DTHRCRIACAO TIMESTAMP NOT NULL,
    DTHRATUALIZACAO TIMESTAMP,
    USUARIOCRIACAO INTEGER NOT NULL,
    USUARIOATUALIZACAO INTEGER,
    CONSTRAINT PK_RELATORIOFILTROS PRIMARY KEY (CODFILTRO)
);
INSERT INTO RELATORIOFILTROS (CODFILTRO, NOME, DESCRICAO, TIPO, SQL_FILTRO, SQL_QUERY, CATEGORIA, ORDEM, OBRIGATORIO, ATIVO, DTHRCRIACAO, DTHRATUALIZACAO, USUARIOCRIACAO, USUARIOATUALIZACAO) SELECT CODFILTRO, NOME, DESCRICAO, TIPO, SQL_FILTRO, SQL_QUERY, CATEGORIA, ORDEM, OBRIGATORIO, ATIVO, DTHRCRIACAO, DTHRATUALIZACAO, USUARIOCRIACAO, USUARIOATUALIZACAO FROM RELATORIO_FILTROS;
-- Ajuste o identity após conferir o MAX(CODFILTRO):
-- ALTER TABLE RELATORIOFILTROS ALTER COLUMN CODFILTRO RESTART WITH <MAX+1>;
DROP TABLE RELATORIO_FILTROS;

-- >>> MODELO_MODO_TEXTO -> MODELOMODOTEXTO
CREATE TABLE MODELOMODOTEXTO (
    CODMODELO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CODUSUARIO INTEGER NOT NULL,
    DTHRULTMODIFICACAO TIMESTAMP,
    CONSTRAINT PK_MODELOMODOTEXTO PRIMARY KEY (CODMODELO),
    CONSTRAINT UNQ_MODELOMODOTEXTO_CODUSUARIO_NOME UNIQUE (CODUSUARIO,NOME)
);
INSERT INTO MODELOMODOTEXTO (CODMODELO, NOME, CODUSUARIO, DTHRULTMODIFICACAO) SELECT CODMODELO, NOME, CODUSUARIO, DTHRULTMODIFICACAO FROM MODELO_MODO_TEXTO;
-- Ajuste o identity após conferir o MAX(CODMODELO):
-- ALTER TABLE MODELOMODOTEXTO ALTER COLUMN CODMODELO RESTART WITH <MAX+1>;
DROP TABLE MODELO_MODO_TEXTO;

-- >>> SCRIPT_VERSOES -> SCRIPTVERSOES
CREATE TABLE SCRIPTVERSOES (
    CODVERSAO INTEGER NOT NULL,
    CODSCRIPTLAUDO INTEGER NOT NULL,
    NUMERO_VERSAO VARCHAR(10) NOT NULL,
    DESCRICAO_ALTERACOES BLOB SUB_TYPE 1,
    ALTERACOES_INTERFACE BLOB SUB_TYPE 1,
    ALTERACOES_CODIGO BLOB SUB_TYPE 1,
    DATA_CRIACAO TIMESTAMP,
    USUARIO_RESPONSAVEL VARCHAR(255) NOT NULL,
    ARQUIVO_JSON BLOB SUB_TYPE 0,
    ARQUIVO_MRD BLOB SUB_TYPE 0,
    ARQUIVO_DLL BLOB SUB_TYPE 0,
    ATIVO CHAR(1),
    APROVADO CHAR(1),
    APROVADO_POR VARCHAR(255),
    DATA_APROVACAO TIMESTAMP,
    OBSERVACOES BLOB SUB_TYPE 1,
    CONSTRAINT PK_SCRIPTVERSOES PRIMARY KEY (CODVERSAO)
);
INSERT INTO SCRIPTVERSOES (CODVERSAO, CODSCRIPTLAUDO, NUMERO_VERSAO, DESCRICAO_ALTERACOES, ALTERACOES_INTERFACE, ALTERACOES_CODIGO, DATA_CRIACAO, USUARIO_RESPONSAVEL, ARQUIVO_JSON, ARQUIVO_MRD, ARQUIVO_DLL, ATIVO, APROVADO, APROVADO_POR, DATA_APROVACAO, OBSERVACOES) SELECT CODVERSAO, CODSCRIPTLAUDO, NUMERO_VERSAO, DESCRICAO_ALTERACOES, ALTERACOES_INTERFACE, ALTERACOES_CODIGO, DATA_CRIACAO, USUARIO_RESPONSAVEL, ARQUIVO_JSON, ARQUIVO_MRD, ARQUIVO_DLL, ATIVO, APROVADO, APROVADO_POR, DATA_APROVACAO, OBSERVACOES FROM SCRIPT_VERSOES;
DROP TABLE SCRIPT_VERSOES;

-- >>> IMPRESSO_VBS -> IMPRESSOVBS
CREATE TABLE IMPRESSOVBS (
    CODIMPRESSO INTEGER NOT NULL,
    SCRIPT_VBS BLOB SUB_TYPE 1 NOT NULL,
    CODUSUARIO INTEGER NOT NULL,
    DTHRULTMODIFICACAO TIMESTAMP NOT NULL,
    CONSTRAINT PK_IMPRESSOVBS PRIMARY KEY (CODIMPRESSO)
);
INSERT INTO IMPRESSOVBS (CODIMPRESSO, SCRIPT_VBS, CODUSUARIO, DTHRULTMODIFICACAO) SELECT CODIMPRESSO, SCRIPT_VBS, CODUSUARIO, DTHRULTMODIFICACAO FROM IMPRESSO_VBS;
DROP TABLE IMPRESSO_VBS;

-- >>> MAPEAMENTO_VARIAVEL -> MAPEAMENTOVARIAVEL
CREATE TABLE MAPEAMENTOVARIAVEL (
    COD_MAPEAMENTO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    COD_VARIAVEL INTEGER NOT NULL,
    COD_UNIVERSAL INTEGER NOT NULL,
    COD_FABRICANTE INTEGER,
    TAG_DICOM VARCHAR(20),
    NOME_EQUIPAMENTO VARCHAR(100),
    CONSTRAINT PK_MAPEAMENTOVARIAVEL PRIMARY KEY (COD_MAPEAMENTO)
);
INSERT INTO MAPEAMENTOVARIAVEL (COD_MAPEAMENTO, COD_VARIAVEL, COD_UNIVERSAL, COD_FABRICANTE, TAG_DICOM, NOME_EQUIPAMENTO) SELECT COD_MAPEAMENTO, COD_VARIAVEL, COD_UNIVERSAL, COD_FABRICANTE, TAG_DICOM, NOME_EQUIPAMENTO FROM MAPEAMENTO_VARIAVEL;
-- Ajuste o identity após conferir o MAX(COD_MAPEAMENTO):
-- ALTER TABLE MAPEAMENTOVARIAVEL ALTER COLUMN COD_MAPEAMENTO RESTART WITH <MAX+1>;
DROP TABLE MAPEAMENTO_VARIAVEL;

-- >>> EQUACOES_LINGUAGEM -> EQUACOESLINGUAGEM
CREATE TABLE EQUACOESLINGUAGEM (
    CODEQUACAO INTEGER NOT NULL,
    CODFORMULA INTEGER NOT NULL,
    CODLINGUAGEM INTEGER NOT NULL,
    EQUACAO BLOB SUB_TYPE 1,
    NOME_FUNCAO VARCHAR(100),
    CODREFERENCIA INTEGER,
    CODUSUARIO INTEGER,
    DTHRULTMODIFICACAO TIMESTAMP,
    CONSTRAINT PK_EQUACOESLINGUAGEM PRIMARY KEY (CODEQUACAO)
);
INSERT INTO EQUACOESLINGUAGEM (CODEQUACAO, CODFORMULA, CODLINGUAGEM, EQUACAO, NOME_FUNCAO, CODREFERENCIA, CODUSUARIO, DTHRULTMODIFICACAO) SELECT CODEQUACAO, CODFORMULA, CODLINGUAGEM, EQUACAO, NOME_FUNCAO, CODREFERENCIA, CODUSUARIO, DTHRULTMODIFICACAO FROM EQUACOES_LINGUAGEM;
DROP TABLE EQUACOES_LINGUAGEM;

-- >>> VARIAVEIS_ALTERNATIVAS -> VARIAVEISALTERNATIVAS
CREATE TABLE VARIAVEISALTERNATIVAS (
    CODVARIAVEL_ALT INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODVARIAVEL INTEGER,
    ALTERNATIVA VARCHAR(255),
    CODUSUARIO INTEGER NOT NULL,
    DTHRULTMODIFICACAO TIMESTAMP NOT NULL,
    CONSTRAINT PK_VARIAVEISALTERNATIVAS PRIMARY KEY (CODVARIAVEL_ALT)
);
INSERT INTO VARIAVEISALTERNATIVAS (CODVARIAVEL_ALT, CODVARIAVEL, ALTERNATIVA, CODUSUARIO, DTHRULTMODIFICACAO) SELECT CODVARIAVEL_ALT, CODVARIAVEL, ALTERNATIVA, CODUSUARIO, DTHRULTMODIFICACAO FROM VARIAVEIS_ALTERNATIVAS;
-- Ajuste o identity após conferir o MAX(CODVARIAVEL_ALT):
-- ALTER TABLE VARIAVEISALTERNATIVAS ALTER COLUMN CODVARIAVEL_ALT RESTART WITH <MAX+1>;
DROP TABLE VARIAVEIS_ALTERNATIVAS;

-- >>> VARIAVEIS_NOMES_CLINICOS -> VARIAVEISNOMESCLINICOS
CREATE TABLE VARIAVEISNOMESCLINICOS (
    CODNOMECLINICO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODVARIAVEL INTEGER NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    CODUSUARIO INTEGER,
    DTHRULTMODIFICACAO TIMESTAMP,
    CONSTRAINT PK_VARIAVEISNOMESCLINICOS PRIMARY KEY (CODNOMECLINICO)
);
INSERT INTO VARIAVEISNOMESCLINICOS (CODNOMECLINICO, CODVARIAVEL, NOME, CODUSUARIO, DTHRULTMODIFICACAO) SELECT CODNOMECLINICO, CODVARIAVEL, NOME, CODUSUARIO, DTHRULTMODIFICACAO FROM VARIAVEIS_NOMES_CLINICOS;
-- Ajuste o identity após conferir o MAX(CODNOMECLINICO):
-- ALTER TABLE VARIAVEISNOMESCLINICOS ALTER COLUMN CODNOMECLINICO RESTART WITH <MAX+1>;
DROP TABLE VARIAVEIS_NOMES_CLINICOS;

-- >>> VARIAVEL_INDEXADA -> VARIAVELINDEXADA
CREATE TABLE VARIAVELINDEXADA (
    CODINDEXADO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODVARIAVEL INTEGER NOT NULL,
    CODUNIDADEMEDIDA INTEGER,
    DESCRICAO VARCHAR(100) NOT NULL,
    FORMULA VARCHAR(200),
    CONSTRAINT PK_VARIAVELINDEXADA PRIMARY KEY (CODINDEXADO)
);
INSERT INTO VARIAVELINDEXADA (CODINDEXADO, CODVARIAVEL, CODUNIDADEMEDIDA, DESCRICAO, FORMULA) SELECT CODINDEXADO, CODVARIAVEL, CODUNIDADEMEDIDA, DESCRICAO, FORMULA FROM VARIAVEL_INDEXADA;
-- Ajuste o identity após conferir o MAX(CODINDEXADO):
-- ALTER TABLE VARIAVELINDEXADA ALTER COLUMN CODINDEXADO RESTART WITH <MAX+1>;
DROP TABLE VARIAVEL_INDEXADA;

-- >>> SCRIPTLAUDO_MRD -> SCRIPTLAUDOMRD
CREATE TABLE SCRIPTLAUDOMRD (
    CODSCRIPTMRD INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODSCRIPTLAUDO INTEGER NOT NULL,
    NOME_ARQUIVO VARCHAR(255),
    ARQUIVO_MRD BLOB SUB_TYPE 0,
    PADRAO CHAR(1) NOT NULL,
    ORDEM INTEGER,
    CODUSUARIO INTEGER,
    DTHRULTMODIFICACAO TIMESTAMP,
    CONSTRAINT PK_SCRIPTLAUDOMRD PRIMARY KEY (CODSCRIPTMRD)
);
INSERT INTO SCRIPTLAUDOMRD (CODSCRIPTMRD, CODSCRIPTLAUDO, NOME_ARQUIVO, ARQUIVO_MRD, PADRAO, ORDEM, CODUSUARIO, DTHRULTMODIFICACAO) SELECT CODSCRIPTMRD, CODSCRIPTLAUDO, NOME_ARQUIVO, ARQUIVO_MRD, PADRAO, ORDEM, CODUSUARIO, DTHRULTMODIFICACAO FROM SCRIPTLAUDO_MRD;
-- Ajuste o identity após conferir o MAX(CODSCRIPTMRD):
-- ALTER TABLE SCRIPTLAUDOMRD ALTER COLUMN CODSCRIPTMRD RESTART WITH <MAX+1>;
DROP TABLE SCRIPTLAUDO_MRD;

-- >>> SCRIPT_ARQUIVOS -> SCRIPTARQUIVOS
CREATE TABLE SCRIPTARQUIVOS (
    CODARQUIVO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODSCRIPTLAUDO INTEGER NOT NULL,
    TIPO VARCHAR(10) NOT NULL,
    CAMINHO VARCHAR(255) NOT NULL,
    NOME_ARQUIVO VARCHAR(100) NOT NULL,
    CODUSUARIO INTEGER NOT NULL,
    DTHRULTMODIFICACAO TIMESTAMP NOT NULL,
    IMAGEM_BASE64 BLOB SUB_TYPE 1,
    CONSTRAINT PK_SCRIPTARQUIVOS PRIMARY KEY (CODARQUIVO)
);
INSERT INTO SCRIPTARQUIVOS (CODARQUIVO, CODSCRIPTLAUDO, TIPO, CAMINHO, NOME_ARQUIVO, CODUSUARIO, DTHRULTMODIFICACAO, IMAGEM_BASE64) SELECT CODARQUIVO, CODSCRIPTLAUDO, TIPO, CAMINHO, NOME_ARQUIVO, CODUSUARIO, DTHRULTMODIFICACAO, IMAGEM_BASE64 FROM SCRIPT_ARQUIVOS;
-- Ajuste o identity após conferir o MAX(CODARQUIVO):
-- ALTER TABLE SCRIPTARQUIVOS ALTER COLUMN CODARQUIVO RESTART WITH <MAX+1>;
DROP TABLE SCRIPT_ARQUIVOS;

-- >>> SCRIPT_APROVACAO_TOKEN -> SCRIPTAPROVACAOTOKEN
CREATE TABLE SCRIPTAPROVACAOTOKEN (
    CODAPROVACAO_TOKEN INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODSCRIPTLAUDO INTEGER NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    CRIADO_EM TIMESTAMP,
    EXPIRA_EM TIMESTAMP NOT NULL,
    USADO INTEGER,
    APROVADO_EM TIMESTAMP,
    REJEITADO_EM TIMESTAMP,
    CONSTRAINT PK_SCRIPTAPROVACAOTOKEN PRIMARY KEY (CODAPROVACAO_TOKEN),
    CONSTRAINT UNQ_SCRIPTAPROVACAOTOKEN_TOKEN UNIQUE (TOKEN)
);
INSERT INTO SCRIPTAPROVACAOTOKEN (CODAPROVACAO_TOKEN, CODSCRIPTLAUDO, TOKEN, CRIADO_EM, EXPIRA_EM, USADO, APROVADO_EM, REJEITADO_EM) SELECT CODAPROVACAO_TOKEN, CODSCRIPTLAUDO, TOKEN, CRIADO_EM, EXPIRA_EM, USADO, APROVADO_EM, REJEITADO_EM FROM SCRIPT_APROVACAO_TOKEN;
-- Ajuste o identity após conferir o MAX(CODAPROVACAO_TOKEN):
-- ALTER TABLE SCRIPTAPROVACAOTOKEN ALTER COLUMN CODAPROVACAO_TOKEN RESTART WITH <MAX+1>;
DROP TABLE SCRIPT_APROVACAO_TOKEN;

-- >>> MODELOS_MENSAGENS -> MODELOSMENSAGENS
CREATE TABLE MODELOSMENSAGENS (
    CODMODELOMENSAGEM INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODGRUPOMENSAGEM INTEGER NOT NULL,
    TITULO VARCHAR(1020) NOT NULL,
    CONTEUDO BLOB SUB_TYPE 1 NOT NULL,
    TIPO_MENSAGEM VARCHAR(200),
    ATIVO SMALLINT NOT NULL,
    CODUSUARIO INTEGER NOT NULL,
    DTHRULTMODIFICACAO TIMESTAMP,
    CONSTRAINT PK_MODELOSMENSAGENS PRIMARY KEY (CODMODELOMENSAGEM)
);
INSERT INTO MODELOSMENSAGENS (CODMODELOMENSAGEM, CODGRUPOMENSAGEM, TITULO, CONTEUDO, TIPO_MENSAGEM, ATIVO, CODUSUARIO, DTHRULTMODIFICACAO) SELECT CODMODELOMENSAGEM, CODGRUPOMENSAGEM, TITULO, CONTEUDO, TIPO_MENSAGEM, ATIVO, CODUSUARIO, DTHRULTMODIFICACAO FROM MODELOS_MENSAGENS;
-- Ajuste o identity após conferir o MAX(CODMODELOMENSAGEM):
-- ALTER TABLE MODELOSMENSAGENS ALTER COLUMN CODMODELOMENSAGEM RESTART WITH <MAX+1>;
DROP TABLE MODELOS_MENSAGENS;

-- >>> SECAO_MODO_TEXTO -> SECAOMODOTEXTO
CREATE TABLE SECAOMODOTEXTO (
    CODSECAO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CODMODELO INTEGER,
    ORDEM INTEGER,
    POSICAO_X INTEGER,
    POSICAO_Y INTEGER,
    LARGURA INTEGER,
    ALTURA INTEGER,
    CONSTRAINT PK_SECAOMODOTEXTO PRIMARY KEY (CODSECAO),
    CONSTRAINT UNQ_SECAOMODOTEXTO_CODMODELO_NOME UNIQUE (CODMODELO,NOME)
);
INSERT INTO SECAOMODOTEXTO (CODSECAO, NOME, CODMODELO, ORDEM, POSICAO_X, POSICAO_Y, LARGURA, ALTURA) SELECT CODSECAO, NOME, CODMODELO, ORDEM, POSICAO_X, POSICAO_Y, LARGURA, ALTURA FROM SECAO_MODO_TEXTO;
-- Ajuste o identity após conferir o MAX(CODSECAO):
-- ALTER TABLE SECAOMODOTEXTO ALTER COLUMN CODSECAO RESTART WITH <MAX+1>;
DROP TABLE SECAO_MODO_TEXTO;

-- >>> RELATORIO_COLUNAS -> RELATORIOCOLUNAS
CREATE TABLE RELATORIOCOLUNAS (
    CODCOLUNA INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODRELATORIO INTEGER NOT NULL,
    NOME_COLUNA VARCHAR(255) NOT NULL,
    POSICAO_COLUNA INTEGER,
    TIPO_COLUNA VARCHAR(50),
    DTHRCRIACAO TIMESTAMP,
    USUARIOCRIACAO INTEGER,
    ATIVO SMALLINT,
    CONSTRAINT PK_RELATORIOCOLUNAS PRIMARY KEY (CODCOLUNA)
);
INSERT INTO RELATORIOCOLUNAS (CODCOLUNA, CODRELATORIO, NOME_COLUNA, POSICAO_COLUNA, TIPO_COLUNA, DTHRCRIACAO, USUARIOCRIACAO, ATIVO) SELECT CODCOLUNA, CODRELATORIO, NOME_COLUNA, POSICAO_COLUNA, TIPO_COLUNA, DTHRCRIACAO, USUARIOCRIACAO, ATIVO FROM RELATORIO_COLUNAS;
-- Ajuste o identity após conferir o MAX(CODCOLUNA):
-- ALTER TABLE RELATORIOCOLUNAS ALTER COLUMN CODCOLUNA RESTART WITH <MAX+1>;
DROP TABLE RELATORIO_COLUNAS;

-- >>> RELATORIO_VALIDACOES -> RELATORIOVALIDACOES
CREATE TABLE RELATORIOVALIDACOES (
    CODVALIDACAO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODRELATORIO INTEGER NOT NULL,
    CODUSUARIO_VALIDADOR INTEGER NOT NULL,
    STATUS_VALIDACAO CHAR(1) NOT NULL,
    METODO_VALIDACAO VARCHAR(100) NOT NULL,
    CRITERIOS_VALIDACAO BLOB SUB_TYPE 1,
    OBSERVACOES BLOB SUB_TYPE 1,
    DTHRVALIDACAO TIMESTAMP,
    DTHRPROXIMA_VALIDACAO TIMESTAMP,
    CONSTRAINT PK_RELATORIOVALIDACOES PRIMARY KEY (CODVALIDACAO)
);
INSERT INTO RELATORIOVALIDACOES (CODVALIDACAO, CODRELATORIO, CODUSUARIO_VALIDADOR, STATUS_VALIDACAO, METODO_VALIDACAO, CRITERIOS_VALIDACAO, OBSERVACOES, DTHRVALIDACAO, DTHRPROXIMA_VALIDACAO) SELECT CODVALIDACAO, CODRELATORIO, CODUSUARIO_VALIDADOR, STATUS_VALIDACAO, METODO_VALIDACAO, CRITERIOS_VALIDACAO, OBSERVACOES, DTHRVALIDACAO, DTHRPROXIMA_VALIDACAO FROM RELATORIO_VALIDACOES;
-- Ajuste o identity após conferir o MAX(CODVALIDACAO):
-- ALTER TABLE RELATORIOVALIDACOES ALTER COLUMN CODVALIDACAO RESTART WITH <MAX+1>;
DROP TABLE RELATORIO_VALIDACOES;

-- >>> SCRIPT_VERSAO_ARQUIVOS -> SCRIPTVERSAOARQUIVOS
CREATE TABLE SCRIPTVERSAOARQUIVOS (
    CODARQUIVO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODVERSAO INTEGER NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    CAMINHO VARCHAR(500),
    NOME_ARQUIVO VARCHAR(255),
    DATA_UPLOAD TIMESTAMP,
    USUARIO_UPLOAD VARCHAR(255),
    CONSTRAINT PK_SCRIPTVERSAOARQUIVOS PRIMARY KEY (CODARQUIVO)
);
INSERT INTO SCRIPTVERSAOARQUIVOS (CODARQUIVO, CODVERSAO, TIPO, CAMINHO, NOME_ARQUIVO, DATA_UPLOAD, USUARIO_UPLOAD) SELECT CODARQUIVO, CODVERSAO, TIPO, CAMINHO, NOME_ARQUIVO, DATA_UPLOAD, USUARIO_UPLOAD FROM SCRIPT_VERSAO_ARQUIVOS;
-- Ajuste o identity após conferir o MAX(CODARQUIVO):
-- ALTER TABLE SCRIPTVERSAOARQUIVOS ALTER COLUMN CODARQUIVO RESTART WITH <MAX+1>;
DROP TABLE SCRIPT_VERSAO_ARQUIVOS;

-- >>> SCRIPT_VERSAO_HISTORICO -> SCRIPTVERSAOHISTORICO
CREATE TABLE SCRIPTVERSAOHISTORICO (
    CODHISTORICO INTEGER NOT NULL,
    CODVERSAO_ORIGEM INTEGER,
    CODVERSAO_DESTINO INTEGER,
    TIPO_ALTERACAO VARCHAR(50) NOT NULL,
    DESCRICAO BLOB SUB_TYPE 1,
    USUARIO VARCHAR(255) NOT NULL,
    DATA_ALTERACAO TIMESTAMP,
    CONSTRAINT PK_SCRIPTVERSAOHISTORICO PRIMARY KEY (CODHISTORICO)
);
INSERT INTO SCRIPTVERSAOHISTORICO (CODHISTORICO, CODVERSAO_ORIGEM, CODVERSAO_DESTINO, TIPO_ALTERACAO, DESCRICAO, USUARIO, DATA_ALTERACAO) SELECT CODHISTORICO, CODVERSAO_ORIGEM, CODVERSAO_DESTINO, TIPO_ALTERACAO, DESCRICAO, USUARIO, DATA_ALTERACAO FROM SCRIPT_VERSAO_HISTORICO;
DROP TABLE SCRIPT_VERSAO_HISTORICO;

-- >>> SCRIPT_VERSAO_MRD -> SCRIPTVERSAOMRD
CREATE TABLE SCRIPTVERSAOMRD (
    CODVERSAOMRD INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODVERSAO INTEGER NOT NULL,
    NOME_ARQUIVO VARCHAR(255),
    ARQUIVO_MRD BLOB SUB_TYPE 0,
    PADRAO CHAR(1) NOT NULL,
    ORDEM INTEGER,
    CONSTRAINT PK_SCRIPTVERSAOMRD PRIMARY KEY (CODVERSAOMRD)
);
INSERT INTO SCRIPTVERSAOMRD (CODVERSAOMRD, CODVERSAO, NOME_ARQUIVO, ARQUIVO_MRD, PADRAO, ORDEM) SELECT CODVERSAOMRD, CODVERSAO, NOME_ARQUIVO, ARQUIVO_MRD, PADRAO, ORDEM FROM SCRIPT_VERSAO_MRD;
-- Ajuste o identity após conferir o MAX(CODVERSAOMRD):
-- ALTER TABLE SCRIPTVERSAOMRD ALTER COLUMN CODVERSAOMRD RESTART WITH <MAX+1>;
DROP TABLE SCRIPT_VERSAO_MRD;

-- -----------------------------------------------------------------------------
-- 3) Recriar FOREIGN KEYS (nomes alinhados aos novos)
-- -----------------------------------------------------------------------------
ALTER TABLE AUTORES ADD CONSTRAINT FK_TIPOAUTOR
  FOREIGN KEY (CODTIPO) REFERENCES TIPOAUTOR (CODTIPO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE CLASSIFICACOES ADD CONSTRAINT FK_CLASSIFICACOES_GRUPO
  FOREIGN KEY (CODGRUPO) REFERENCES GRUPOSCLASSIFICACOES (CODGRUPO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE CONFIGURACOESSISTEMA ADD CONSTRAINT FK_CONFIGURACOES_USUARIO
  FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ECOCARDIOGRAFIAANALISES ADD CONSTRAINT FK_ECOCARDIOGRAFIA_USER
  FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE EQUACOESLINGUAGEM ADD CONSTRAINT FK_EQUACOESLINGUAGEM_FORMULA
  FOREIGN KEY (CODFORMULA) REFERENCES FORMULAS (CODFORMULA)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE EQUACOESLINGUAGEM ADD CONSTRAINT FK_EQUACOESLINGUAGEM_LINGUAGEM
  FOREIGN KEY (CODLINGUAGEM) REFERENCES TIPOLINGUAGEM (CODLINGUAGEM)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE EQUACOESLINGUAGEM ADD CONSTRAINT FK_EQUACOESLINGUAGEM_REFERENCIA
  FOREIGN KEY (CODREFERENCIA) REFERENCES REFERENCIA (CODREFERENCIA)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE IMPRESSOVBS ADD CONSTRAINT FK_IMPRESSOVBS_IMPRESSO
  FOREIGN KEY (CODIMPRESSO) REFERENCES IMPRESSO (CODIMPRESSO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE IMPRESSOVBS ADD CONSTRAINT FK_IMPRESSOVBS_USUARIO
  FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE MAPEAMENTOVARIAVEL ADD CONSTRAINT FK_CODIGO
  FOREIGN KEY (COD_UNIVERSAL) REFERENCES CODIGOUNIVERSAL (COD_UNIVERSAL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE MAPEAMENTOVARIAVEL ADD CONSTRAINT FK_FABRICANTE
  FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTE (COD_FABRICANTE)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE MAPEAMENTOVARIAVEL ADD CONSTRAINT FK_VARIAVEL
  FOREIGN KEY (COD_VARIAVEL) REFERENCES VARIAVEIS (CODVARIAVEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE MODELOSMENSAGENS ADD CONSTRAINT FK_MODELOSMENSAGENS_GRUPO
  FOREIGN KEY (CODGRUPOMENSAGEM) REFERENCES GRUPOSMENSAGENS (CODGRUPOMENSAGEM)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE MODELOMODOTEXTO ADD CONSTRAINT MODELO_CODUSUARIO_FK
  FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE MODULORELATORIO ADD CONSTRAINT FK_MODULO_REL_USUARIO_ATUALIZACAO
  FOREIGN KEY (USUARIOATUALIZACAO) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE MODULORELATORIO ADD CONSTRAINT FK_MODULO_REL_USUARIO_CRIACAO
  FOREIGN KEY (USUARIOCRIACAO) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE NORMALIDADE ADD CONSTRAINT FK_NORMALIDADE_MODOAQUISICAO
  FOREIGN KEY (CODMODOAQUISICAO) REFERENCES MODOAQUISICAO (CODMODO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE NORMALIDADE ADD CONSTRAINT FK_NORMALIDADE_POPULACAO
  FOREIGN KEY (CODPOPULACAO) REFERENCES POPULACAOREFERENCIA (CODPOPULACAO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE REFERENCIA ADD CONSTRAINT FK_TIPOREF
  FOREIGN KEY (CODTIPOREF) REFERENCES TIPOREFERENCIA (CODTIPOREF)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE RELATORIOS ADD CONSTRAINT FK_RELATORIO_MODULO
  FOREIGN KEY (CODMODULO) REFERENCES MODULORELATORIO (CODMODULO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE RELATORIOCOLUNAS ADD CONSTRAINT FK_RELATORIOCOLUNAS_RELATORIOS
  FOREIGN KEY (CODRELATORIO) REFERENCES RELATORIOS (CODRELATORIO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE RELATORIOFILTROS ADD CONSTRAINT FK_RELATORIOFILTROS_USUARIO_A
  FOREIGN KEY (USUARIOATUALIZACAO) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE RELATORIOFILTROS ADD CONSTRAINT FK_RELATORIOFILTROS_USUARIO_C
  FOREIGN KEY (USUARIOCRIACAO) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE RELATORIOVALIDACOES ADD CONSTRAINT FK_VALIDACOES_RELATORIO
  FOREIGN KEY (CODRELATORIO) REFERENCES RELATORIOS (CODRELATORIO)
  ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE RELATORIOVALIDACOES ADD CONSTRAINT FK_VALIDACOES_USUARIO
  FOREIGN KEY (CODUSUARIO_VALIDADOR) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE SCRIPTLAUDOMRD ADD CONSTRAINT FK_SCRIPT_MRD_SCRIPT
  FOREIGN KEY (CODSCRIPTLAUDO) REFERENCES SCRIPTLAUDO (CODSCRIPTLAUDO)
  ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE SCRIPTAPROVACAOTOKEN ADD CONSTRAINT FK_SCRIPTAPROVACAOTOKEN_SCRIPT
  FOREIGN KEY (CODSCRIPTLAUDO) REFERENCES SCRIPTLAUDO (CODSCRIPTLAUDO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE SCRIPTARQUIVOS ADD CONSTRAINT FK_SCRIPTARQUIVOS_CODSCRIPTLAUDO
  FOREIGN KEY (CODSCRIPTLAUDO) REFERENCES SCRIPTLAUDO (CODSCRIPTLAUDO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE SCRIPTVERSAOARQUIVOS ADD CONSTRAINT FK_SCRIPTVERSAOARQUIVOS_VERSAO
  FOREIGN KEY (CODVERSAO) REFERENCES SCRIPTVERSOES (CODVERSAO)
  ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE SCRIPTVERSAOHISTORICO ADD CONSTRAINT FK_SCRIPTVERSAOHISTORICO_DESTINO
  FOREIGN KEY (CODVERSAO_DESTINO) REFERENCES SCRIPTVERSOES (CODVERSAO)
  ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE SCRIPTVERSAOHISTORICO ADD CONSTRAINT FK_SCRIPTVERSAOHISTORICO_ORIGEM
  FOREIGN KEY (CODVERSAO_ORIGEM) REFERENCES SCRIPTVERSOES (CODVERSAO)
  ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE SCRIPTVERSAOMRD ADD CONSTRAINT FK_VERSAO_MRD_VERSAO
  FOREIGN KEY (CODVERSAO) REFERENCES SCRIPTVERSOES (CODVERSAO)
  ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE SCRIPTVERSOES ADD CONSTRAINT FK_SCRIPTVERSOES_SCRIPT
  FOREIGN KEY (CODSCRIPTLAUDO) REFERENCES SCRIPTLAUDO (CODSCRIPTLAUDO)
  ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE SECAOMODOTEXTO ADD CONSTRAINT SECAO_CODMODELO_FK
  FOREIGN KEY (CODMODELO) REFERENCES MODELOMODOTEXTO (CODMODELO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE SECAO_VARIAVEL ADD CONSTRAINT SECAO_VARIAVEL_CODSECAO_FK
  FOREIGN KEY (CODSECAO) REFERENCES SECAOMODOTEXTO (CODSECAO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE SISTEMA_MODULO ADD CONSTRAINT FK_SISMOD_MODULO
  FOREIGN KEY (CODMODULO) REFERENCES MODULORELATORIO (CODMODULO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVEIS ADD CONSTRAINT FK_VARIAVEIS_GRUPO
  FOREIGN KEY (CODGRUPO) REFERENCES GRUPOSVARIAVEIS (CODGRUPO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVEISALTERNATIVAS ADD CONSTRAINT VARIAVEISALTERNATIVAS_CODUSUARIO_FK
  FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO (CODUSUARIO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVEISALTERNATIVAS ADD CONSTRAINT VARIAVEISALTERNATIVAS_FK
  FOREIGN KEY (CODVARIAVEL) REFERENCES VARIAVEIS (CODVARIAVEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVEISNOMESCLINICOS ADD CONSTRAINT FK_VNC_CODVARIAVEL
  FOREIGN KEY (CODVARIAVEL) REFERENCES VARIAVEIS (CODVARIAVEL)
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE VARIAVEL_CODIGO_UNIVERSAL ADD CONSTRAINT FK_CODIGOUNIVERSAL
  FOREIGN KEY (COD_UNIVERSAL) REFERENCES CODIGOUNIVERSAL (COD_UNIVERSAL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVELINDEXADA ADD CONSTRAINT VARIAVELINDEXADA_FK
  FOREIGN KEY (CODVARIAVEL) REFERENCES VARIAVEIS (CODVARIAVEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVELINDEXADA ADD CONSTRAINT VARIAVEL_UNIDADEMEDIDA_FK
  FOREIGN KEY (CODUNIDADEMEDIDA) REFERENCES UNIDADEMEDIDA (CODUNIDADEMEDIDA)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVEL_METODO ADD CONSTRAINT FK_METODO
  FOREIGN KEY (CODMETODO) REFERENCES METODOANALISE (CODMETODO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVEL_METODO ADD CONSTRAINT FK_MODO
  FOREIGN KEY (CODMODO) REFERENCES MODOAQUISICAO (CODMODO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- -----------------------------------------------------------------------------
-- 4) Validação (descomente após rodar)
-- -----------------------------------------------------------------------------
/*
SELECT TRIM(RDB$RELATION_NAME) AS TABELA_ANTIGA
  FROM RDB$RELATIONS
 WHERE RDB$SYSTEM_FLAG = 0 AND RDB$VIEW_BLR IS NULL
   AND TRIM(RDB$RELATION_NAME) IN ('SCRIPT_VERSAO_ARQUIVOS', 'SCRIPT_VERSAO_HISTORICO', 'SCRIPT_VERSAO_MRD', 'SCRIPT_APROVACAO_TOKEN', 'SCRIPT_ARQUIVOS', 'SCRIPT_VERSOES', 'SCRIPTLAUDO_MRD', 'VARIAVEIS_NOMES_CLINICOS', 'VARIAVEIS_ALTERNATIVAS', 'VARIAVEL_INDEXADA', 'RELATORIO_VALIDACOES', 'RELATORIO_COLUNAS', 'RELATORIO_FILTROS', 'ECOCARDIOGRAFIA_ANALISES', 'CONFIGURACOES_SISTEMA', 'POPULACAO_REFERENCIA', 'GRUPOS_CLASSIFICACOES', 'MAPEAMENTO_VARIAVEL', 'EQUACOES_LINGUAGEM', 'MODELOS_MENSAGENS', 'GRUPOS_MENSAGENS', 'GRUPOS_VARIAVEIS', 'SECAO_MODO_TEXTO', 'MODELO_MODO_TEXTO', 'CODIGO_UNIVERSAL', 'MODULO_RELATORIO', 'METODO_ANALISE', 'MODO_AQUISICAO', 'TIPO_REFERENCIA', 'IMPRESSO_VBS', 'TIPO_AUTOR');

SELECT TRIM(RDB$RELATION_NAME) AS TABELA_NOVA
  FROM RDB$RELATIONS
 WHERE RDB$SYSTEM_FLAG = 0 AND RDB$VIEW_BLR IS NULL
   AND TRIM(RDB$RELATION_NAME) IN ('SCRIPTVERSAOARQUIVOS', 'SCRIPTVERSAOHISTORICO', 'SCRIPTVERSAOMRD', 'SCRIPTAPROVACAOTOKEN', 'SCRIPTARQUIVOS', 'SCRIPTVERSOES', 'SCRIPTLAUDOMRD', 'VARIAVEISNOMESCLINICOS', 'VARIAVEISALTERNATIVAS', 'VARIAVELINDEXADA', 'RELATORIOVALIDACOES', 'RELATORIOCOLUNAS', 'RELATORIOFILTROS', 'ECOCARDIOGRAFIAANALISES', 'CONFIGURACOESSISTEMA', 'POPULACAOREFERENCIA', 'GRUPOSCLASSIFICACOES', 'MAPEAMENTOVARIAVEL', 'EQUACOESLINGUAGEM', 'MODELOSMENSAGENS', 'GRUPOSMENSAGENS', 'GRUPOSVARIAVEIS', 'SECAOMODOTEXTO', 'MODELOMODOTEXTO', 'CODIGOUNIVERSAL', 'MODULORELATORIO', 'METODOANALISE', 'MODOAQUISICAO', 'TIPOREFERENCIA', 'IMPRESSOVBS', 'TIPOAUTOR')
 ORDER BY 1;
*/
