SET AUTODDL ON;

-- =============================================================================
-- Padroniza constraints INTEG_* do REFERENCIAS.FDB (Firebird 5)
--
-- Padrão de nomes:
--   PK_<TABELA>
--   FK_<TABELA>_<COLUNA>
--   UNQ_<TABELA>_<COLUNA>
--
-- Ordem obrigatória (Firebird não permite DROP de PK referenciada):
--   1) DROP FKs que apontam para PKs INTEG_* (e FKs INTEG_* restantes)
--   2) DROP UNIQUE INTEG_*
--   3) DROP PRIMARY KEY INTEG_*
--   4) ADD PRIMARY KEY nomeadas
--   5) ADD UNIQUE nomeadas
--   6) ADD FOREIGN KEY (recria as removidas; INTEG_* passam a ter nome)
--
-- Faça backup antes. Rode em uma janela e confira erros.
-- Idempotência: NÃO é idempotente — rode uma vez.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) DROP FOREIGN KEYS (dependentes de PKs INTEG_* + FKs INTEG_*)
-- -----------------------------------------------------------------------------

-- -> CLIENTES
ALTER TABLE PAINEIS DROP CONSTRAINT FK_PAINEIS_CLIENTES;

-- -> CODIGO_UNIVERSAL
ALTER TABLE MAPEAMENTO_VARIAVEL DROP CONSTRAINT FK_CODIGO;
ALTER TABLE VARIAVEL_CODIGO_UNIVERSAL DROP CONSTRAINT FK_CODIGO_UNIVERSAL;

-- -> ESPECIALIDADE
ALTER TABLE REFERENCIA DROP CONSTRAINT FK_REFERENCIA_ESPECIALIDADE;
ALTER TABLE VARIAVEL_ESPECIALIDADE DROP CONSTRAINT FK_ESPECIALIDADE;

-- -> FABRICANTE
ALTER TABLE MAPEAMENTO_VARIAVEL DROP CONSTRAINT FK_FABRICANTE;

-- -> GRUPOS_MENSAGENS
ALTER TABLE MODELOS_MENSAGENS DROP CONSTRAINT INTEG_352;

-- -> IMPRESSO
ALTER TABLE IMPRESSO_VBS DROP CONSTRAINT FK_IMPRESSO_VBS_IMPRESSO;

-- -> METODO_ANALISE
ALTER TABLE VARIAVEL_METODO DROP CONSTRAINT FK_METODO;

-- -> MODO_AQUISICAO
ALTER TABLE NORMALIDADE DROP CONSTRAINT FK_NORMALIDADE_MODO_AQUISICAO;
ALTER TABLE VARIAVEL_METODO DROP CONSTRAINT FK_MODO;

-- -> MODULOSSISTEMA
ALTER TABLE PAINEIS DROP CONSTRAINT FK_PAINEIS_MODULOSSISTEMA;

-- -> PACOTESCOMERCIAIS / PAINEIS
ALTER TABLE PAINEIS_PACOTES DROP CONSTRAINT INTEG_312;
ALTER TABLE PAINEIS_PACOTES DROP CONSTRAINT INTEG_310;
ALTER TABLE LOGALTERACOES DROP CONSTRAINT FK_LOG_PAINEL;
ALTER TABLE VERSOESPAINEL DROP CONSTRAINT FK_VERSOESPAINEL_PAINEIS;

-- -> POPULACAO_REFERENCIA
ALTER TABLE NORMALIDADE DROP CONSTRAINT FK_NORMALIDADE_POPULACAO;

-- -> TIPOLINGUAGEM / demais FKs INTEG_* de EQUACOES_LINGUAGEM
ALTER TABLE EQUACOES_LINGUAGEM DROP CONSTRAINT INTEG_123;
ALTER TABLE EQUACOES_LINGUAGEM DROP CONSTRAINT INTEG_122;
ALTER TABLE EQUACOES_LINGUAGEM DROP CONSTRAINT INTEG_124;

-- -> TIPO_AUTOR / TIPO_REFERENCIA
ALTER TABLE AUTORES DROP CONSTRAINT FK_TIPO_AUTOR;
ALTER TABLE REFERENCIA DROP CONSTRAINT FK_TIPOREF;

-- -> VERSOESPAINEL
ALTER TABLE ARQUIVOSVERSOES DROP CONSTRAINT FK_ARQUIVOSVERSOES_VERSOES;
ALTER TABLE CONFIGURACOESAPI DROP CONSTRAINT FK_CONFIGAPI_VERSOES;
ALTER TABLE CONFIGURACOESPOWERBI DROP CONSTRAINT FK_CONFIGPOWERBI_VERSOES;
ALTER TABLE DIMENSOES DROP CONSTRAINT FK_DIMENSOES_VERSOESPAINEL;
ALTER TABLE FONTESDADOS DROP CONSTRAINT FK_FONTESDADOS_VERSOESPAINEL;
ALTER TABLE IMAGENSPAINEL DROP CONSTRAINT FK_IMAGENSPAINEL_VERSAO;
ALTER TABLE LOGALTERACOES DROP CONSTRAINT FK_LOG_VERSAO;
ALTER TABLE METRICAS DROP CONSTRAINT FK_METRICAS_VERSOESPAINEL;

-- FK INTEG_* que não depende de PK INTEG_* (só padronização de nome)
ALTER TABLE SCRIPT_APROVACAO_TOKEN DROP CONSTRAINT INTEG_497;

-- -----------------------------------------------------------------------------
-- 2) DROP UNIQUE INTEG_*
-- -----------------------------------------------------------------------------
ALTER TABLE MODULOSSISTEMA DROP CONSTRAINT INTEG_297;
ALTER TABLE PACOTESCOMERCIAIS DROP CONSTRAINT INTEG_301;
ALTER TABLE SCRIPT_APROVACAO_TOKEN DROP CONSTRAINT INTEG_495;
ALTER TABLE VARIAVEISPACCONECTADO DROP CONSTRAINT INTEG_349;
ALTER TABLE VERSOESPAINEL DROP CONSTRAINT INTEG_319;

-- -----------------------------------------------------------------------------
-- 3) DROP PRIMARY KEY INTEG_*
-- -----------------------------------------------------------------------------
ALTER TABLE CLIENTES DROP CONSTRAINT INTEG_291;
ALTER TABLE CODIGO_UNIVERSAL DROP CONSTRAINT INTEG_125;
ALTER TABLE CONFIGURACOESAPI DROP CONSTRAINT INTEG_365;
ALTER TABLE CONFIGURACOESPOWERBI DROP CONSTRAINT INTEG_361;
ALTER TABLE CONFIGURACOES_SISTEMA DROP CONSTRAINT INTEG_372;
ALTER TABLE DIMENSOES DROP CONSTRAINT INTEG_327;
ALTER TABLE ECOCARDIOGRAFIA_ANALISES DROP CONSTRAINT INTEG_250;
ALTER TABLE EQUACOES_LINGUAGEM DROP CONSTRAINT INTEG_121;
ALTER TABLE ESPECIALIDADE DROP CONSTRAINT INTEG_13;
ALTER TABLE FABRICANTE DROP CONSTRAINT INTEG_129;
ALTER TABLE FONTESDADOS DROP CONSTRAINT INTEG_330;
ALTER TABLE GRUPOS_MENSAGENS DROP CONSTRAINT INTEG_333;
ALTER TABLE IMPRESSO DROP CONSTRAINT INTEG_447;
ALTER TABLE MAPEAMENTO_VARIAVEL DROP CONSTRAINT INTEG_131;
ALTER TABLE METODO_ANALISE DROP CONSTRAINT INTEG_193;
ALTER TABLE METRICAS DROP CONSTRAINT INTEG_324;
ALTER TABLE MODELOSFRASES DROP CONSTRAINT INTEG_227;
ALTER TABLE MODELOS_MENSAGENS DROP CONSTRAINT INTEG_350;
ALTER TABLE MODO_AQUISICAO DROP CONSTRAINT INTEG_191;
ALTER TABLE MODULOSSISTEMA DROP CONSTRAINT INTEG_295;
ALTER TABLE PACIENTECONECTADOMSG DROP CONSTRAINT INTEG_229;
ALTER TABLE PACOTESCOMERCIAIS DROP CONSTRAINT INTEG_299;
ALTER TABLE PAINEIS DROP CONSTRAINT INTEG_303;
ALTER TABLE PAINEIS_PACOTES DROP CONSTRAINT INTEG_313;
ALTER TABLE POPULACAO_REFERENCIA DROP CONSTRAINT INTEG_215;
ALTER TABLE PROTOCOLOSOLICITACAO DROP CONSTRAINT INTEG_586;
ALTER TABLE RELATORIO_FILTROS DROP CONSTRAINT INTEG_477;
ALTER TABLE SCRIPT_APROVACAO_TOKEN DROP CONSTRAINT INTEG_492;
ALTER TABLE SOLICITACAO_PROCEDIMENTO DROP CONSTRAINT INTEG_590;
ALTER TABLE TIPOLINGUAGEM DROP CONSTRAINT INTEG_94;
ALTER TABLE TIPO_AUTOR DROP CONSTRAINT INTEG_213;
ALTER TABLE TIPO_REFERENCIA DROP CONSTRAINT INTEG_211;
ALTER TABLE VARIAVEISPACCONECTADO DROP CONSTRAINT INTEG_347;
ALTER TABLE VARIAVEL_INDEXADA DROP CONSTRAINT INTEG_90;
ALTER TABLE VARIAVEL_METODO DROP CONSTRAINT INTEG_202;
ALTER TABLE VERSOESPAINEL DROP CONSTRAINT INTEG_314;

-- -----------------------------------------------------------------------------
-- 4) ADD PRIMARY KEY nomeadas
-- -----------------------------------------------------------------------------
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CODCLIENTE);
ALTER TABLE CODIGO_UNIVERSAL ADD CONSTRAINT PK_CODIGO_UNIVERSAL PRIMARY KEY (COD_UNIVERSAL);
ALTER TABLE CONFIGURACOESAPI ADD CONSTRAINT PK_CONFIGURACOESAPI PRIMARY KEY (CODCONFIGAPI);
ALTER TABLE CONFIGURACOESPOWERBI ADD CONSTRAINT PK_CONFIGURACOESPOWERBI PRIMARY KEY (CODCONFIGPOWERBI);
ALTER TABLE CONFIGURACOES_SISTEMA ADD CONSTRAINT PK_CONFIGURACOES_SISTEMA PRIMARY KEY (ID);
ALTER TABLE DIMENSOES ADD CONSTRAINT PK_DIMENSOES PRIMARY KEY (CODDIMENSAO);
ALTER TABLE ECOCARDIOGRAFIA_ANALISES ADD CONSTRAINT PK_ECOCARDIOGRAFIA_ANALISES PRIMARY KEY (ID);
ALTER TABLE EQUACOES_LINGUAGEM ADD CONSTRAINT PK_EQUACOES_LINGUAGEM PRIMARY KEY (CODEQUACAO);
ALTER TABLE ESPECIALIDADE ADD CONSTRAINT PK_ESPECIALIDADE PRIMARY KEY (CODESPECIALIDADE);
ALTER TABLE FABRICANTE ADD CONSTRAINT PK_FABRICANTE PRIMARY KEY (COD_FABRICANTE);
ALTER TABLE FONTESDADOS ADD CONSTRAINT PK_FONTESDADOS PRIMARY KEY (CODFONTEDADOS);
ALTER TABLE GRUPOS_MENSAGENS ADD CONSTRAINT PK_GRUPOS_MENSAGENS PRIMARY KEY (CODGRUPOMENSAGEM);
ALTER TABLE IMPRESSO ADD CONSTRAINT PK_IMPRESSO PRIMARY KEY (CODIMPRESSO);
ALTER TABLE MAPEAMENTO_VARIAVEL ADD CONSTRAINT PK_MAPEAMENTO_VARIAVEL PRIMARY KEY (COD_MAPEAMENTO);
ALTER TABLE METODO_ANALISE ADD CONSTRAINT PK_METODO_ANALISE PRIMARY KEY (CODMETODO);
ALTER TABLE METRICAS ADD CONSTRAINT PK_METRICAS PRIMARY KEY (CODMETRICA);
ALTER TABLE MODELOSFRASES ADD CONSTRAINT PK_MODELOSFRASES PRIMARY KEY (ID);
ALTER TABLE MODELOS_MENSAGENS ADD CONSTRAINT PK_MODELOS_MENSAGENS PRIMARY KEY (CODMODELOMENSAGEM);
ALTER TABLE MODO_AQUISICAO ADD CONSTRAINT PK_MODO_AQUISICAO PRIMARY KEY (CODMODO);
ALTER TABLE MODULOSSISTEMA ADD CONSTRAINT PK_MODULOSSISTEMA PRIMARY KEY (CODMODULO);
ALTER TABLE PACIENTECONECTADOMSG ADD CONSTRAINT PK_PACIENTECONECTADOMSG PRIMARY KEY (ID);
ALTER TABLE PACOTESCOMERCIAIS ADD CONSTRAINT PK_PACOTESCOMERCIAIS PRIMARY KEY (CODPACOTECOMERCIAL);
ALTER TABLE PAINEIS ADD CONSTRAINT PK_PAINEIS PRIMARY KEY (CODPAINEL);
ALTER TABLE PAINEIS_PACOTES ADD CONSTRAINT PK_PAINEIS_PACOTES PRIMARY KEY (CODPAINEL, CODPACOTECOMERCIAL);
ALTER TABLE POPULACAO_REFERENCIA ADD CONSTRAINT PK_POPULACAO_REFERENCIA PRIMARY KEY (CODPOPULACAO);
ALTER TABLE PROTOCOLOSOLICITACAO ADD CONSTRAINT PK_PROTOCOLOSOLICITACAO PRIMARY KEY (CODPROTOCOLO);
ALTER TABLE RELATORIO_FILTROS ADD CONSTRAINT PK_RELATORIO_FILTROS PRIMARY KEY (CODFILTRO);
ALTER TABLE SCRIPT_APROVACAO_TOKEN ADD CONSTRAINT PK_SCRIPT_APROVACAO_TOKEN PRIMARY KEY (CODAPROVACAO_TOKEN);
ALTER TABLE SOLICITACAO_PROCEDIMENTO ADD CONSTRAINT PK_SOLICITACAO_PROCEDIMENTO PRIMARY KEY (CODPROTOCOLO, CODTABELAPROCEDIMENTO);
ALTER TABLE TIPOLINGUAGEM ADD CONSTRAINT PK_TIPOLINGUAGEM PRIMARY KEY (CODLINGUAGEM);
ALTER TABLE TIPO_AUTOR ADD CONSTRAINT PK_TIPO_AUTOR PRIMARY KEY (CODTIPO);
ALTER TABLE TIPO_REFERENCIA ADD CONSTRAINT PK_TIPO_REFERENCIA PRIMARY KEY (CODTIPOREF);
ALTER TABLE VARIAVEISPACCONECTADO ADD CONSTRAINT PK_VARIAVEISPACCONECTADO PRIMARY KEY (CODVARIAVEISPACCONECTADO);
ALTER TABLE VARIAVEL_INDEXADA ADD CONSTRAINT PK_VARIAVEL_INDEXADA PRIMARY KEY (CODINDEXADO);
ALTER TABLE VARIAVEL_METODO ADD CONSTRAINT PK_VARIAVEL_METODO PRIMARY KEY (CODRELACIONAMENTO);
ALTER TABLE VERSOESPAINEL ADD CONSTRAINT PK_VERSOESPAINEL PRIMARY KEY (CODVERSAOPAINEL);

-- -----------------------------------------------------------------------------
-- 5) ADD UNIQUE nomeadas
-- -----------------------------------------------------------------------------
ALTER TABLE MODULOSSISTEMA ADD CONSTRAINT UNQ_MODULOSSISTEMA_NOME UNIQUE (NOME);
ALTER TABLE PACOTESCOMERCIAIS ADD CONSTRAINT UNQ_PACOTESCOMERCIAIS_NOME UNIQUE (NOME);
ALTER TABLE SCRIPT_APROVACAO_TOKEN ADD CONSTRAINT UNQ_SCRIPT_APROVACAO_TOKEN_TOKEN UNIQUE (TOKEN);
ALTER TABLE VARIAVEISPACCONECTADO ADD CONSTRAINT UNQ_VARIAVEISPACCONECTADO_VARIAVEL UNIQUE (VARIAVEL);
ALTER TABLE VERSOESPAINEL ADD CONSTRAINT UNQ_VERSOESPAINEL_PAINEL_VERSAO UNIQUE (CODPAINEL, NUMEROVERSAO);

-- -----------------------------------------------------------------------------
-- 6) ADD FOREIGN KEYS (recria dependências + padroniza as que eram INTEG_*)
-- -----------------------------------------------------------------------------

-- CLIENTES
ALTER TABLE PAINEIS ADD CONSTRAINT FK_PAINEIS_CLIENTES
  FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES (CODCLIENTE)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- CODIGO_UNIVERSAL
ALTER TABLE MAPEAMENTO_VARIAVEL ADD CONSTRAINT FK_CODIGO
  FOREIGN KEY (COD_UNIVERSAL) REFERENCES CODIGO_UNIVERSAL (COD_UNIVERSAL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVEL_CODIGO_UNIVERSAL ADD CONSTRAINT FK_CODIGO_UNIVERSAL
  FOREIGN KEY (COD_UNIVERSAL) REFERENCES CODIGO_UNIVERSAL (COD_UNIVERSAL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- ESPECIALIDADE
ALTER TABLE REFERENCIA ADD CONSTRAINT FK_REFERENCIA_ESPECIALIDADE
  FOREIGN KEY (CODESPECIALIDADE) REFERENCES ESPECIALIDADE (CODESPECIALIDADE)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVEL_ESPECIALIDADE ADD CONSTRAINT FK_ESPECIALIDADE
  FOREIGN KEY (CODESPECIALIDADE) REFERENCES ESPECIALIDADE (CODESPECIALIDADE)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- FABRICANTE
ALTER TABLE MAPEAMENTO_VARIAVEL ADD CONSTRAINT FK_FABRICANTE
  FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTE (COD_FABRICANTE)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- GRUPOS_MENSAGENS (era INTEG_352)
ALTER TABLE MODELOS_MENSAGENS ADD CONSTRAINT FK_MODELOS_MENSAGENS_GRUPO
  FOREIGN KEY (CODGRUPOMENSAGEM) REFERENCES GRUPOS_MENSAGENS (CODGRUPOMENSAGEM)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- IMPRESSO
ALTER TABLE IMPRESSO_VBS ADD CONSTRAINT FK_IMPRESSO_VBS_IMPRESSO
  FOREIGN KEY (CODIMPRESSO) REFERENCES IMPRESSO (CODIMPRESSO)
  ON UPDATE RESTRICT ON DELETE CASCADE;

-- METODO_ANALISE
ALTER TABLE VARIAVEL_METODO ADD CONSTRAINT FK_METODO
  FOREIGN KEY (CODMETODO) REFERENCES METODO_ANALISE (CODMETODO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- MODO_AQUISICAO
ALTER TABLE NORMALIDADE ADD CONSTRAINT FK_NORMALIDADE_MODO_AQUISICAO
  FOREIGN KEY (CODMODOAQUISICAO) REFERENCES MODO_AQUISICAO (CODMODO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VARIAVEL_METODO ADD CONSTRAINT FK_MODO
  FOREIGN KEY (CODMODO) REFERENCES MODO_AQUISICAO (CODMODO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- MODULOSSISTEMA
ALTER TABLE PAINEIS ADD CONSTRAINT FK_PAINEIS_MODULOSSISTEMA
  FOREIGN KEY (CODMODULO) REFERENCES MODULOSSISTEMA (CODMODULO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- PAINEIS / PACOTESCOMERCIAIS (eram INTEG_310 / INTEG_312)
ALTER TABLE PAINEIS_PACOTES ADD CONSTRAINT FK_PAINEIS_PACOTES_PAINEL
  FOREIGN KEY (CODPAINEL) REFERENCES PAINEIS (CODPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE PAINEIS_PACOTES ADD CONSTRAINT FK_PAINEIS_PACOTES_PACOTE
  FOREIGN KEY (CODPACOTECOMERCIAL) REFERENCES PACOTESCOMERCIAIS (CODPACOTECOMERCIAL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE LOGALTERACOES ADD CONSTRAINT FK_LOG_PAINEL
  FOREIGN KEY (CODPAINEL) REFERENCES PAINEIS (CODPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE VERSOESPAINEL ADD CONSTRAINT FK_VERSOESPAINEL_PAINEIS
  FOREIGN KEY (CODPAINEL) REFERENCES PAINEIS (CODPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- POPULACAO_REFERENCIA
ALTER TABLE NORMALIDADE ADD CONSTRAINT FK_NORMALIDADE_POPULACAO
  FOREIGN KEY (CODPOPULACAO) REFERENCES POPULACAO_REFERENCIA (CODPOPULACAO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- EQUACOES_LINGUAGEM (eram INTEG_122/123/124)
ALTER TABLE EQUACOES_LINGUAGEM ADD CONSTRAINT FK_EQUACOES_LINGUAGEM_FORMULA
  FOREIGN KEY (CODFORMULA) REFERENCES FORMULAS (CODFORMULA)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE EQUACOES_LINGUAGEM ADD CONSTRAINT FK_EQUACOES_LINGUAGEM_LINGUAGEM
  FOREIGN KEY (CODLINGUAGEM) REFERENCES TIPOLINGUAGEM (CODLINGUAGEM)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE EQUACOES_LINGUAGEM ADD CONSTRAINT FK_EQUACOES_LINGUAGEM_REFERENCIA
  FOREIGN KEY (CODREFERENCIA) REFERENCES REFERENCIA (CODREFERENCIA)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- TIPO_AUTOR / TIPO_REFERENCIA
ALTER TABLE AUTORES ADD CONSTRAINT FK_TIPO_AUTOR
  FOREIGN KEY (CODTIPO) REFERENCES TIPO_AUTOR (CODTIPO)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE REFERENCIA ADD CONSTRAINT FK_TIPOREF
  FOREIGN KEY (CODTIPOREF) REFERENCES TIPO_REFERENCIA (CODTIPOREF)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- VERSOESPAINEL
ALTER TABLE ARQUIVOSVERSOES ADD CONSTRAINT FK_ARQUIVOSVERSOES_VERSOES
  FOREIGN KEY (CODVERSAOPAINEL) REFERENCES VERSOESPAINEL (CODVERSAOPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE CONFIGURACOESAPI ADD CONSTRAINT FK_CONFIGAPI_VERSOES
  FOREIGN KEY (CODVERSAOPAINEL) REFERENCES VERSOESPAINEL (CODVERSAOPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE CONFIGURACOESPOWERBI ADD CONSTRAINT FK_CONFIGPOWERBI_VERSOES
  FOREIGN KEY (CODVERSAOPAINEL) REFERENCES VERSOESPAINEL (CODVERSAOPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE DIMENSOES ADD CONSTRAINT FK_DIMENSOES_VERSOESPAINEL
  FOREIGN KEY (CODVERSAOPAINEL) REFERENCES VERSOESPAINEL (CODVERSAOPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE FONTESDADOS ADD CONSTRAINT FK_FONTESDADOS_VERSOESPAINEL
  FOREIGN KEY (CODVERSAOPAINEL) REFERENCES VERSOESPAINEL (CODVERSAOPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE IMAGENSPAINEL ADD CONSTRAINT FK_IMAGENSPAINEL_VERSAO
  FOREIGN KEY (CODVERSAOPAINEL) REFERENCES VERSOESPAINEL (CODVERSAOPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE LOGALTERACOES ADD CONSTRAINT FK_LOG_VERSAO
  FOREIGN KEY (CODVERSAOPAINEL) REFERENCES VERSOESPAINEL (CODVERSAOPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE METRICAS ADD CONSTRAINT FK_METRICAS_VERSOESPAINEL
  FOREIGN KEY (CODVERSAOPAINEL) REFERENCES VERSOESPAINEL (CODVERSAOPAINEL)
  ON UPDATE RESTRICT ON DELETE RESTRICT;

-- SCRIPT_APROVACAO_TOKEN (era INTEG_497)
ALTER TABLE SCRIPT_APROVACAO_TOKEN ADD CONSTRAINT FK_SCRIPT_APROVACAO_TOKEN_SCRIPT
  FOREIGN KEY (CODSCRIPTLAUDO) REFERENCES SCRIPTLAUDO (CODSCRIPTLAUDO)
  ON UPDATE RESTRICT ON DELETE CASCADE;

-- =============================================================================
-- Verificação (opcional): deve retornar 0 linhas
-- =============================================================================
-- SELECT TRIM(RDB$RELATION_NAME) AS TABELA,
--        TRIM(RDB$CONSTRAINT_NAME) AS CONSTRAINT_NOME,
--        TRIM(RDB$CONSTRAINT_TYPE) AS TIPO
--   FROM RDB$RELATION_CONSTRAINTS
--  WHERE TRIM(RDB$CONSTRAINT_NAME) STARTING WITH 'INTEG_'
--    AND TRIM(RDB$RELATION_NAME) NOT STARTING WITH 'RDB$'
--  ORDER BY 3, 1;
