SET AUTODDL ON;

-- Grupo PT. CLASSIFICACOES.NOME é UNIQUE no banco, então Normal/Leve/Moderado/Grave
-- já existentes (Classificações Básicas) são reaproveitados e movidos para este grupo.

INSERT INTO GRUPOSCLASSIFICACOES (CODGRUPO, NOME, CODUSUARIO, DTHRULTMODIFICACAO)
SELECT (SELECT MAX(CODGRUPO) FROM GRUPOSCLASSIFICACOES) + 1,
       'Gravidade eco (PT)',
       COALESCE((SELECT MIN(CODUSUARIO) FROM USUARIO), 1),
       CURRENT_TIMESTAMP
FROM RDB$DATABASE
WHERE NOT EXISTS (
    SELECT 1 FROM GRUPOSCLASSIFICACOES WHERE UPPER(NOME) = UPPER('Gravidade eco (PT)')
);

UPDATE CLASSIFICACOES
   SET CODGRUPO = (SELECT CODGRUPO FROM GRUPOSCLASSIFICACOES WHERE UPPER(NOME) = UPPER('Gravidade eco (PT)'))
 WHERE UPPER(NOME) IN ('NORMAL', 'LEVE', 'MODERADO', 'GRAVE')
   AND EXISTS (SELECT 1 FROM GRUPOSCLASSIFICACOES WHERE UPPER(NOME) = UPPER('Gravidade eco (PT)'));

INSERT INTO CLASSIFICACOES (CODCLASSIFICACAO, NOME, CODGRUPO, CODUSUARIO, DTHRULTMODIFICACAO)
SELECT (SELECT MAX(CODCLASSIFICACAO) FROM CLASSIFICACOES) + 1,
       'Normal', g.CODGRUPO, COALESCE((SELECT MIN(CODUSUARIO) FROM USUARIO), 1), CURRENT_TIMESTAMP
FROM GRUPOSCLASSIFICACOES g
WHERE UPPER(g.NOME) = UPPER('Gravidade eco (PT)')
  AND NOT EXISTS (SELECT 1 FROM CLASSIFICACOES c WHERE UPPER(c.NOME) = 'NORMAL');

INSERT INTO CLASSIFICACOES (CODCLASSIFICACAO, NOME, CODGRUPO, CODUSUARIO, DTHRULTMODIFICACAO)
SELECT (SELECT MAX(CODCLASSIFICACAO) FROM CLASSIFICACOES) + 1,
       'Leve', g.CODGRUPO, COALESCE((SELECT MIN(CODUSUARIO) FROM USUARIO), 1), CURRENT_TIMESTAMP
FROM GRUPOSCLASSIFICACOES g
WHERE UPPER(g.NOME) = UPPER('Gravidade eco (PT)')
  AND NOT EXISTS (SELECT 1 FROM CLASSIFICACOES c WHERE UPPER(c.NOME) = 'LEVE');

INSERT INTO CLASSIFICACOES (CODCLASSIFICACAO, NOME, CODGRUPO, CODUSUARIO, DTHRULTMODIFICACAO)
SELECT (SELECT MAX(CODCLASSIFICACAO) FROM CLASSIFICACOES) + 1,
       'Moderado', g.CODGRUPO, COALESCE((SELECT MIN(CODUSUARIO) FROM USUARIO), 1), CURRENT_TIMESTAMP
FROM GRUPOSCLASSIFICACOES g
WHERE UPPER(g.NOME) = UPPER('Gravidade eco (PT)')
  AND NOT EXISTS (SELECT 1 FROM CLASSIFICACOES c WHERE UPPER(c.NOME) = 'MODERADO');

INSERT INTO CLASSIFICACOES (CODCLASSIFICACAO, NOME, CODGRUPO, CODUSUARIO, DTHRULTMODIFICACAO)
SELECT (SELECT MAX(CODCLASSIFICACAO) FROM CLASSIFICACOES) + 1,
       'Grave', g.CODGRUPO, COALESCE((SELECT MIN(CODUSUARIO) FROM USUARIO), 1), CURRENT_TIMESTAMP
FROM GRUPOSCLASSIFICACOES g
WHERE UPPER(g.NOME) = UPPER('Gravidade eco (PT)')
  AND NOT EXISTS (SELECT 1 FROM CLASSIFICACOES c WHERE UPPER(c.NOME) = 'GRAVE');
