SET NAMES ISO8859_1;
SET TERM ^;
EXECUTE BLOCK AS
BEGIN
  UPDATE ESPECIALIDADE SET NOME = 'CARDIOLOGIA', DESCRICAO = 'CARDIOLOGIA', CODUSUARIO = 9, DTHRULTMODIFICACAO = CURRENT_TIMESTAMP
    WHERE CODESPECIALIDADE = 7 AND UPPER(NOME) = 'CARDIOLOGIA';
  UPDATE ESPECIALIDADE SET NOME = 'ECOCARDIOGRAFIA', DESCRICAO = 'ECOCARDIOGRAFIA', CODUSUARIO = 9, DTHRULTMODIFICACAO = CURRENT_TIMESTAMP
    WHERE CODESPECIALIDADE = 9 AND UPPER(NOME) = 'ECOCARDIOGRAFIA';
  UPDATE ESPECIALIDADE SET NOME = 'ULTRA-SONOGRAFIA', DESCRICAO = 'ULTRA-SONOGRAFIA', CODUSUARIO = 9, DTHRULTMODIFICACAO = CURRENT_TIMESTAMP
    WHERE CODESPECIALIDADE = 4 AND (UPPER(NOME) = 'ULTRASSONOGRAFIA' OR UPPER(NOME) = 'ULTRA-SONOGRAFIA');
END
^
EXECUTE BLOCK AS
DECLARE VARIABLE V_NOME VARCHAR(100);
DECLARE VARIABLE V_EXISTS INTEGER;
BEGIN
  V_NOME = 'ALERGOLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'ANATOMIA PATOLÓGICA E CITOPATOLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'ANESTESIOLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'ANGIOLOGIA - CIRURGIA VASCULAR E LINFÁTICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CARDIOLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CIRURGIA CARDÍACA-HEMODINÂMICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CIRURGIA DA MÃO';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CIRURGIA DE CABEÇA E PESCOÇO';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CIRURGIA DE MAMA (MASTOLOGIA)';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CIRURGIA DO APARELHO DIGESTIVO, ORGÃOS, ANEXOS E PAREDE ABDOMINAL';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CIRURGIA ENDOCRINOLÓGICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CIRURGIA PEDIÁTRICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CIRURGIA PLÁSTICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CIRURGIA TORÁCICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'CONSULTÓRIO';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'DERMATOLOGIA (CLÍNICO-CIRÚRGICA)';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'ELECTRENCEFALOGRAFIA E NEUROFISIOLOGIA CLÍNICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'ENDOSCOPIA DIGESTIVA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'ENDOSCOPIA PERORAL';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'GENÉTICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'GINECOLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'HEMOTERAPIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'MEDICINA FÍSICA E REABILITAÇÃO (FISIATRIA)';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'MEDICINA NUCLEAR';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'MICROCIRURGIA RECONSTRUTIVA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'NEFROLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'NEUROCIRURGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'NUTRIÇÃO PARENTERAL E ENTERAL';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'OFTALMOLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'ORTOPEDIA E TRAUMATOLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'OTORRINOLARINGOLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'OUTROS';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'PATOLOGIA CLÍNICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'QUIMIOTERAPIA DO CÂNCER';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'RADIODIAGNÓSTICO';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'RADIOTERAPIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'RESSONÂNCIA MAGNÉTICA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'TISIOPNEUMOLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'TOMOGRAFIA COMPUTADORIZADA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'ULTRA-SONOGRAFIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'UROLOGIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'ECOCARDIOGRAFIA';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
  V_NOME = 'VASCULAR';
  SELECT COUNT(*) FROM ESPECIALIDADE WHERE UPPER(NOME) = UPPER(:V_NOME) INTO :V_EXISTS;
  IF (V_EXISTS = 0) THEN
  BEGIN
    INSERT INTO ESPECIALIDADE (NOME, DESCRICAO, CODUSUARIO, DTHRULTMODIFICACAO)
    VALUES (:V_NOME, :V_NOME, 9, CURRENT_TIMESTAMP);
  END
END^
SET TERM ;^
SELECT COUNT(*) AS QTD FROM ESPECIALIDADE;
SELECT CODESPECIALIDADE, NOME FROM ESPECIALIDADE ORDER BY NOME;
